Repository frzyc/genshin-optimizer, pull requests merged in 2024-08, with the labels that each got.

#2373 add debug command
  apps/somnia/src/commands/debug.ts
  apps/somnia/src/main.ts
Labels: deploySomnia

#2383 Add loadout handling + some UI for SRO
  apps/sr-frontend/src/app/App.tsx
  apps/sr-frontend/src/app/CharacterSelector.tsx
  apps/sr-frontend/src/app/PageHome.tsx
  libs/sr/consts/src/character.ts
  libs/sr/db/src/Database/DataManagers/BuildDataManager.ts
  libs/sr/db/src/Database/DataManagers/BuildTcDataManager.ts
  libs/sr/db/src/Database/DataManagers/CharMetaDataManager.ts
  libs/sr/db/src/Database/DataManagers/CharacterDataManager.ts
  libs/sr/db/src/Database/DataManagers/LightConeDataManager.ts
  libs/sr/db/src/Database/DataManagers/LoadoutDataManager.ts
  libs/sr/db/src/Database/DataManagers/OptConfigDataManager.ts
  libs/sr/db/src/Database/DataManagers/RelicDataManager.ts
  libs/sr/db/src/Database/DataManagers/TeamDataManager.test.ts
  libs/sr/db/src/Database/DataManagers/TeamDataManager.ts
  libs/sr/db/src/Database/DataManagers/index.ts
  libs/sr/db/src/Database/Database.test.ts
  libs/sr/db/src/Database/Database.ts
  libs/sr/formula/src/data/common/prep.ts
  libs/sr/page-team/src/TeamSettings/index.tsx
  libs/sr/page-team/src/TeammateDisplay/Tabs/Optimize/index.tsx
  libs/sr/page-team/src/TeammateDisplay/index.tsx
  libs/sr/page-team/src/index.tsx
  libs/sr/page-team/tsconfig.json
  libs/sr/ui/src/Character/LocationAutocomplete.tsx
  libs/sr/ui/src/Context/CharacterContext.tsx
  libs/sr/ui/src/Context/LoadoutContext.tsx
  libs/sr/ui/src/Context/index.tsx
  libs/sr/ui/src/Hook/index.ts
  libs/sr/ui/src/Hook/useLoadout.ts
  libs/sr/ui/src/Hook/useTeam.ts
  libs/sr/ui/src/Provider/DatabaseProvider.tsx
  libs/sr/ui/src/Provider/LoadoutProvider.tsx
  libs/sr/ui/src/Provider/TeamCalcProvider.tsx
  libs/sr/ui/src/Provider/index.tsx
  libs/sr/ui/src/Team/TeamCard.tsx
  libs/sr/ui/src/Team/TeamCharacterSelector.tsx
Labels: SRO

#2392 minimal ui-sheets for SRO
  libs/sr/assets/src/index.ts
  libs/sr/formula-ui/.babelrc
  libs/sr/formula-ui/.eslintrc.json
  libs/sr/formula-ui/README.md
  libs/sr/formula-ui/project.json
  libs/sr/formula-ui/src/char/consts.d.ts
  libs/sr/formula-ui/src/char/sheets/RuanMei.tsx
  libs/sr/formula-ui/src/char/sheets/index.ts
  libs/sr/formula-ui/src/index.ts
  libs/sr/formula-ui/src/util.tsx
  libs/sr/formula-ui/tsconfig.eslint.json
  libs/sr/formula-ui/tsconfig.json
  libs/sr/formula-ui/tsconfig.lib.json
  libs/sr/formula/src/index.ts
  libs/sr/stats/src/index.ts
  tsconfig.base.json
Labels: SRO

#2380 [SRO] Add svgicons
  .yarn/cache/@types-react-npm-18.2.68-b36136e75c-76786df04f.zip
  .yarn/cache/@types-react-npm-18.3.1-5744cb1fe5-9224ef319a.zip
  libs/sr/svgicons/.babelrc
  libs/sr/svgicons/.eslintrc.json
  libs/sr/svgicons/README.md
  libs/sr/svgicons/project.json
  libs/sr/svgicons/src/components/SlotIcon.tsx
  libs/sr/svgicons/src/components/StatIcon.tsx
  libs/sr/svgicons/src/icons/Assets/CharacterIcon.tsx
  libs/sr/svgicons/src/icons/Assets/DetailsIcon.tsx
  libs/sr/svgicons/src/icons/Assets/EidolonIcon.tsx
  libs/sr/svgicons/src/icons/Assets/LightConeIcon.tsx
  libs/sr/svgicons/src/icons/Assets/RelicIcon.tsx
  libs/sr/svgicons/src/icons/Assets/TeamsIcon.tsx
  libs/sr/svgicons/src/icons/Assets/TracesIcon.tsx
  libs/sr/svgicons/src/icons/Elements/FireIcon.tsx
  libs/sr/svgicons/src/icons/Elements/IceIcon.tsx
  libs/sr/svgicons/src/icons/Elements/ImaginaryIcon.tsx
  libs/sr/svgicons/src/icons/Elements/LightningIcon.tsx
  libs/sr/svgicons/src/icons/Elements/PhysicalIcon.tsx
  libs/sr/svgicons/src/icons/Elements/QuantumIcon.tsx
  libs/sr/svgicons/src/icons/Elements/WindIcon.tsx
  libs/sr/svgicons/src/icons/RelicSlot/BodyIcon.tsx
  libs/sr/svgicons/src/icons/RelicSlot/FeetIcon.tsx
  libs/sr/svgicons/src/icons/RelicSlot/HandsIcon.tsx
  libs/sr/svgicons/src/icons/RelicSlot/HeadIcon.tsx
  libs/sr/svgicons/src/icons/RelicSlot/RopeIcon.tsx
  libs/sr/svgicons/src/icons/RelicSlot/SphereIcon.tsx
  libs/sr/svgicons/src/icons/Stats/AtkIcon.tsx
  libs/sr/svgicons/src/icons/Stats/BrEffIcon.tsx
  libs/sr/svgicons/src/icons/Stats/CritDmgIcon.tsx
  libs/sr/svgicons/src/icons/Stats/CritRateIcon.tsx
  libs/sr/svgicons/src/icons/Stats/DefIcon.tsx
  libs/sr/svgicons/src/icons/Stats/EffIcon.tsx
  libs/sr/svgicons/src/icons/Stats/EffResIcon.tsx
  libs/sr/svgicons/src/icons/Stats/EnerRegenIcon.tsx
  libs/sr/svgicons/src/icons/Stats/HealBoostIcon.tsx
  libs/sr/svgicons/src/icons/Stats/HpIcon.tsx
  libs/sr/svgicons/src/icons/Stats/SpdIcon.tsx
  libs/sr/svgicons/src/index.ts
  libs/sr/svgicons/tsconfig.eslint.json
  libs/sr/svgicons/tsconfig.json
  libs/sr/svgicons/tsconfig.lib.json
  package.json
  tsconfig.base.json
  yarn.lock
Labels: SRO

#2398 Add -1 to beginning of skillparamlist
  libs/sr/stats/Data/Characters/Acheron.json
  libs/sr/stats/Data/Characters/Argenti.json
  libs/sr/stats/Data/Characters/Arlan.json
  libs/sr/stats/Data/Characters/Asta.json
  libs/sr/stats/Data/Characters/Aventurine.json
  libs/sr/stats/Data/Characters/Bailu.json
  libs/sr/stats/Data/Characters/BlackSwan.json
  libs/sr/stats/Data/Characters/Blade.json
  libs/sr/stats/Data/Characters/Boothill.json
  libs/sr/stats/Data/Characters/Bronya.json
  libs/sr/stats/Data/Characters/Clara.json
  libs/sr/stats/Data/Characters/DanHeng.json
  libs/sr/stats/Data/Characters/DanHengImbibitorLunae.json
  libs/sr/stats/Data/Characters/DrRatio.json
  libs/sr/stats/Data/Characters/Firefly.json
  libs/sr/stats/Data/Characters/FuXuan.json
  libs/sr/stats/Data/Characters/Gallagher.json
  libs/sr/stats/Data/Characters/Gepard.json
  libs/sr/stats/Data/Characters/Guinaifen.json
  libs/sr/stats/Data/Characters/Hanya.json
  libs/sr/stats/Data/Characters/Herta.json
  libs/sr/stats/Data/Characters/Himeko.json
  libs/sr/stats/Data/Characters/Hook.json
  libs/sr/stats/Data/Characters/Huohuo.json
  libs/sr/stats/Data/Characters/Jade.json
  libs/sr/stats/Data/Characters/JingYuan.json
  libs/sr/stats/Data/Characters/Jingliu.json
  libs/sr/stats/Data/Characters/Kafka.json
  libs/sr/stats/Data/Characters/Luka.json
  libs/sr/stats/Data/Characters/Luocha.json
  libs/sr/stats/Data/Characters/Lynx.json
  libs/sr/stats/Data/Characters/March7th.json
  libs/sr/stats/Data/Characters/March7thTheHunt.json
  libs/sr/stats/Data/Characters/Misha.json
  libs/sr/stats/Data/Characters/Natasha.json
  libs/sr/stats/Data/Characters/Pela.json
  libs/sr/stats/Data/Characters/Qingque.json
  libs/sr/stats/Data/Characters/Robin.json
  libs/sr/stats/Data/Characters/RuanMei.json
  libs/sr/stats/Data/Characters/Sampo.json
  libs/sr/stats/Data/Characters/Seele.json
  libs/sr/stats/Data/Characters/Serval.json
  libs/sr/stats/Data/Characters/SilverWolf.json
  libs/sr/stats/Data/Characters/Sparkle.json
  libs/sr/stats/Data/Characters/Sushang.json
  libs/sr/stats/Data/Characters/Tingyun.json
  libs/sr/stats/Data/Characters/TopazAndNumby.json
  libs/sr/stats/Data/Characters/TrailblazerFireF.json
  libs/sr/stats/Data/Characters/TrailblazerFireM.json
  libs/sr/stats/Data/Characters/TrailblazerImaginaryF.json
  libs/sr/stats/Data/Characters/TrailblazerImaginaryM.json
  libs/sr/stats/Data/Characters/TrailblazerPhysicalF.json
  libs/sr/stats/Data/Characters/TrailblazerPhysicalM.json
  libs/sr/stats/Data/Characters/Welt.json
  libs/sr/stats/Data/Characters/Xueyi.json
  libs/sr/stats/Data/Characters/Yanqing.json
  libs/sr/stats/Data/Characters/Yukong.json
  libs/sr/stats/Data/Characters/Yunli.json
  libs/sr/stats/src/allStat_gen.json
  libs/sr/stats/src/executors/gen-stats/src/characterData.ts
Labels: SRO

#2413 Fix crash when optimizing with Scroll set
  libs/gi/sheets/src/Artifacts/ScrollOfTheHeroOfCinderCity/index.tsx
Labels: bug, fix ASAP

#2412 [SRO] Fix missing main stat strings
  libs/sr/consts/src/relic.ts
  libs/sr/dm-localization/assets/locales/chs/statKey_gen.json
  libs/sr/dm-localization/assets/locales/cht/statKey_gen.json
  libs/sr/dm-localization/assets/locales/de/statKey_gen.json
  libs/sr/dm-localization/assets/locales/en/statKey_gen.json
  libs/sr/dm-localization/assets/locales/es/statKey_gen.json
  libs/sr/dm-localization/assets/locales/fr/statKey_gen.json
  libs/sr/dm-localization/assets/locales/id/statKey_gen.json
  libs/sr/dm-localization/assets/locales/ja/statKey_gen.json
  libs/sr/dm-localization/assets/locales/ko/statKey_gen.json
  libs/sr/dm-localization/assets/locales/pt/statKey_gen.json
  libs/sr/dm-localization/assets/locales/ru/statKey_gen.json
  libs/sr/dm-localization/assets/locales/th/statKey_gen.json
  libs/sr/dm-localization/assets/locales/vi/statKey_gen.json
  libs/sr/dm-localization/src/executors/gen-locale/lib/hashData.ts
Labels: SRO

#2416 [SRO] Add basic relic card UI
  apps/sr-frontend/src/styles.scss
  libs/sr/dm-localization/assets/locales/chs/slotKey_gen.json
  libs/sr/dm-localization/assets/locales/cht/slotKey_gen.json
  libs/sr/dm-localization/assets/locales/de/slotKey_gen.json
  libs/sr/dm-localization/assets/locales/en/slotKey_gen.json
  libs/sr/dm-localization/assets/locales/es/slotKey_gen.json
  libs/sr/dm-localization/assets/locales/fr/slotKey_gen.json
  libs/sr/dm-localization/assets/locales/id/slotKey_gen.json
  libs/sr/dm-localization/assets/locales/ja/slotKey_gen.json
  libs/sr/dm-localization/assets/locales/ko/slotKey_gen.json
  libs/sr/dm-localization/assets/locales/pt/slotKey_gen.json
  libs/sr/dm-localization/assets/locales/ru/slotKey_gen.json
  libs/sr/dm-localization/assets/locales/th/slotKey_gen.json
  libs/sr/dm-localization/assets/locales/vi/slotKey_gen.json
  libs/sr/dm-localization/src/executors/gen-locale/executor.ts
  libs/sr/dm-localization/src/executors/gen-locale/lib/hashData.ts
  libs/sr/localization/assets/locales/en/relic.json
  libs/sr/ui/src/Character/LocationAutocomplete.tsx
  libs/sr/ui/src/Relic/RelicCard.tsx
  libs/sr/ui/src/Relic/RelicInventory.tsx
  libs/sr/ui/src/Relic/RelicTrans.tsx
  libs/sr/ui/src/Relic/index.tsx
  libs/sr/ui/src/Relic/util.ts
Labels: SRO

#2425 [SRO] Prettify header
  apps/frontend/src/app/Header.tsx
  apps/sr-frontend/src/app/Header.tsx
  libs/common/ui/src/components/HeaderTally.tsx
  libs/common/ui/src/components/index.ts
Labels: SRO

#2422 Pando conditional UI
  apps/gi-frontend/src/app/teams/[teamId]/TalentContent.tsx
  libs/pando/ui-sheet/src/components/DocumentDisplay.tsx
  libs/pando/ui-sheet/src/types/conditional.ts
  libs/sr/assets/src/index.ts
  libs/sr/db/src/Types/conditional.ts
  libs/sr/formula-ui/src/char/sheets/RuanMei.tsx
  libs/sr/page-team/src/TeammateDisplay/Tabs/TalentContent.tsx
Labels: Pando
