Repository frzyc/genshin-optimizer, pull requests merged in 2024-03, with the labels that each got.

#1662 Combine Loadout and Build settings into a singular popup
  apps/frontend/src/app/PageTeam/CharacterDisplay/Build/BuildEditorBtn.tsx
  apps/frontend/src/app/PageTeam/CharacterDisplay/Content.tsx
  apps/frontend/src/app/PageTeam/CharacterDisplay/LoadoutSettingElement.tsx
Labels: teams

#1680 fix team resonance not toggleable
  apps/frontend/src/app/Components/Conditional/ConditionalSelector.tsx
  apps/frontend/src/app/Formula/api.tsx
  apps/frontend/src/app/PageTeam/TeamSetting/index.tsx
  apps/frontend/src/app/ReactHooks/useTeamData.tsx
  libs/gi/db/src/Database/DataManagers/TeamCharacterDataManager.ts
  libs/gi/db/src/Database/DataManagers/TeamDataManager.ts
  libs/gi/db/src/Database/migrate.ts
Labels: fix ASAP

#1686 Reduce columns for stat display
  apps/frontend/src/app/Components/Character/StatDisplayComponent.tsx
  apps/frontend/src/app/Components/FieldDisplay.tsx
  apps/frontend/src/app/PageTeam/CharacterDisplay/Tabs/TabOverview/index.tsx
  apps/frontend/src/app/PageTeam/CharacterDisplay/Tabs/TabTheorycraft/index.tsx
Labels: fix ASAP

#1743 Fix bug with Add Build To List
  apps/frontend/src/app/PageTeam/CharacterDisplay/Tabs/TabOptimize/Components/ChartCard/index.tsx
Labels: fix ASAP

#1745 Fix incorrect usage of main stat display value for optimization
  apps/frontend/src/app/PageTeam/CharacterDisplay/Tabs/TabOptimize/foreground.ts
  apps/frontend/src/app/PageTeam/CharacterDisplay/Tabs/TabUpgradeOpt/upOpt.ts
Labels: fix ASAP

#1750 Convert KQMSButton from Dialog to Modal
  apps/frontend/src/app/PageTeam/CharacterDisplay/Tabs/TabTheorycraft/KQMSButton.tsx
  libs/gi/localization/assets/locales/en/page_character.json
Labels: fix ASAP

#1790 fix team export
  libs/gi/db/src/Database/DataManagers/TeamDataManager.ts
Labels: bug, fix ASAP

#1807 BuildDisplayItem fixes for build comparisons done from character editor
  apps/frontend/src/app/PageTeam/CharacterDisplay/Build/EquipBuildModal.tsx
  apps/frontend/src/app/PageTeam/CharacterDisplay/Tabs/TabOptimize/Components/BuildDisplayItem.tsx
Labels: fix ASAP

#1826 Fix team exim
  libs/gi/db/src/Database/DataManagers/BuildTcDataManager.ts
  libs/gi/db/src/Database/DataManagers/TeamDataManager.test.ts
  libs/gi/db/src/Database/DataManagers/TeamDataManager.ts
Labels: fix ASAP

#1839 Fix compare crash
  apps/frontend/src/app/Components/CompareBuildButton.tsx
Labels: fix ASAP

#1858 resolve info & units from nodes in UI
  apps/frontend/src/app/PageTeam/CharacterDisplay/Tabs/TabOptimize/Components/ChartCard/index.tsx
  apps/frontend/src/app/PageTeam/CharacterDisplay/Tabs/TabOptimize/Components/OptimizationTargetEditorList.tsx
  apps/frontend/src/app/PageTeam/CharacterDisplay/Tabs/TabOptimize/Components/TargetSelectorModal.tsx
  apps/frontend/src/app/PageTeam/CharacterDisplay/Tabs/TabOptimize/index.tsx
  apps/frontend/src/app/PageTeam/CharacterDisplay/Tabs/TabUpgradeOpt/index.tsx
Labels: fix ASAP
