Repository frzyc/genshin-optimizer, pull requests merged in 2024-04, with the labels that each got.

#1939 Tc worker fix
  libs/gi/page-team/src/CharacterDisplay/Tabs/TabTheorycraft/index.tsx
  libs/gi/solver-tc/src/index.ts
Labels: fix ASAP

#1713 Basic character editor
  apps/sr-frontend/src/app/App.tsx
  apps/sr-frontend/src/app/Character.tsx
  apps/sr-frontend/src/app/CharacterSelector.tsx
  apps/sr-frontend/vite.config.ts
  libs/sr/consts/src/common.ts
  libs/sr/ui/src/Character/AbilityDropdown.tsx
  libs/sr/ui/src/Character/index.tsx
Labels: SRO

#1958 Use GO page on go-next
  apps/gi-frontend-next/src/app/[locale]/DatabaseWrapper.tsx
  apps/gi-frontend-next/src/app/[locale]/artifacts/page.tsx
  apps/gi-frontend-next/src/app/[locale]/layout.tsx
  libs/common/ui/src/components/NextImage.tsx
  libs/common/ui/src/components/index.ts
  libs/common/ui/src/hooks/useOnScreen.tsx
  libs/gi/db/src/Database/ArtCharDatabase.ts
  libs/gi/db/src/Database/DataEntries/DisplayOptimizeEntry.ts
  libs/gi/db/src/index.ts
  libs/gi/db/src/thread.ts
  libs/gi/page-team/src/CharacterDisplay/Tabs/TabOptimize/index.tsx
  libs/gi/page-team/src/CharacterDisplay/Tabs/TabUpgradeOpt/index.tsx
  libs/gi/ui/src/components/artifact/ArtifactCard.tsx
  libs/gi/ui/src/components/character/CharIconSideElement.tsx
  libs/gi/ui/src/hooks/index.ts
  libs/gi/ui/src/hooks/useNumWorkers.tsx
Labels: go-next

#1969 fix team page rerender after revalidating character
  libs/gi/page-team/src/index.tsx
Labels: bug

#1971 Rename sr-opt and fix built count being wrong
  apps/sr-frontend/src/app/Optimize.tsx
  libs/sr/opt/README.md
  libs/sr/opt/src/index.ts
  libs/sr/solver/.eslintrc.json
  libs/sr/solver/README.md
  libs/sr/solver/jest.config.ts
  libs/sr/solver/project.json
  libs/sr/solver/src/childWorker.ts
  libs/sr/solver/src/common.ts
  libs/sr/solver/src/index.ts
  libs/sr/solver/src/parentWorker.ts
  libs/sr/solver/src/solver.ts
  libs/sr/solver/tsconfig.json
  libs/sr/solver/tsconfig.lib.json
  libs/sr/solver/tsconfig.spec.json
  tsconfig.base.json
Labels: SRO

#1983 Split worker work more evenly
  libs/sr/solver/src/parentWorker.ts
Labels: SRO

#1988 Add header to SRO
  apps/frontend/src/app/App.tsx
  apps/sr-frontend/src/app/App.tsx
  apps/sr-frontend/src/app/Header.tsx
  apps/sr-frontend/src/app/PageHome.tsx
  libs/common/ui/src/components/ScrollTop.tsx
  libs/common/ui/src/components/index.ts
Labels: SRO

#1881 1549 add relic viewer
  apps/sr-frontend/src/app/PageHome.tsx
  libs/sr/ui/src/Relic/RelicCard.tsx
  libs/sr/ui/src/Relic/RelicInventory.tsx
  libs/sr/ui/src/Relic/index.tsx
Labels: SRO

#1853 Light cone viewer (#1551)
  apps/sr-frontend/src/app/PageHome.tsx
  libs/sr/ui/src/LightCone/LightConeCard.tsx
  libs/sr/ui/src/LightCone/LightConeInventory.tsx
  libs/sr/ui/src/LightCone/index.tsx
Labels: SRO

#1985 Update clean-pr.yml to merge on divergent branches
  .github/workflows/clean-pr.yml
Labels: CI
