Repository frzyc/genshin-optimizer, pull requests merged in 2025-02, with the labels that each got.

#2668 Add debugging view for SRO
  libs/common/ui/src/components/CodeBlock.tsx
  libs/gi/page-doc/src/index.tsx
  libs/pando/ui-sheet/src/components/FieldDisplay.tsx
  libs/pando/ui-sheet/src/context/DebugReadContext.tsx
  libs/pando/ui-sheet/src/context/index.ts
  libs/sr/page-team/src/ComboEditor.tsx
  libs/sr/page-team/src/DebugDisplay.tsx
  libs/sr/page-team/src/TeammateDisplay.tsx
  libs/sr/page-team/src/index.tsx
Labels: SRO

#2670 ZO add icons to stat display, minor fixes
  libs/zzz/consts/src/common.ts
  libs/zzz/page-optimize/src/BaseStatCard.tsx
  libs/zzz/page-optimize/src/BuildsDisplay.tsx
  libs/zzz/page-optimize/src/Optimize.tsx
  libs/zzz/page-optimize/src/StatFilterCard.tsx
  libs/zzz/page-optimize/src/StatsDisplay.tsx
  libs/zzz/svgicons/src/components/StatIcon.tsx
  libs/zzz/ui/src/Character/StatDisplay.tsx
Labels: ZO

#2673 ZO fix Woodpecker number
  libs/zzz/consts/src/disc.ts
Labels: ZO

#2671 Change zzz submodule to shallow
  .gitmodules
Labels: ZO

#2685 ZO fix Chaotic Metal 4p
  libs/zzz/consts/src/disc.ts
Labels: ZO

#2689 Fix vertical centering of images in char circle
  libs/zzz/ui/src/Character/CharIconCircleElement.tsx
Labels: ZO

#2675 ZO: Character Page
  apps/zzz-frontend/src/app/App.tsx
  apps/zzz-frontend/src/app/Header.tsx
  apps/zzz-frontend/src/styles.scss
  libs/zzz/assets/src/common/discBackdrop.png
  libs/zzz/assets/src/common/drive.png
  libs/zzz/assets/src/common/index.ts
  libs/zzz/assets/src/common/skill/index.ts
  libs/zzz/assets/src/index.ts
  libs/zzz/consts/src/character.ts
  libs/zzz/page-characters/.babelrc
  libs/zzz/page-characters/.eslintrc.json
  libs/zzz/page-characters/README.md
  libs/zzz/page-characters/project.json
  libs/zzz/page-characters/src/index.tsx
  libs/zzz/page-characters/tsconfig.eslint.json
  libs/zzz/page-characters/tsconfig.json
  libs/zzz/page-characters/tsconfig.lib.json
  libs/zzz/theme/src/Theme.tsx
  libs/zzz/ui/src/Character/CharacterCard.tsx
  libs/zzz/ui/src/Character/card/CharacterCardContent.tsx
  libs/zzz/ui/src/Character/card/CharacterCardEquipment.tsx
  libs/zzz/ui/src/Character/card/index.ts
  libs/zzz/ui/src/Character/index.tsx
  libs/zzz/ui/src/index.tsx
  libs/zzz/ui/src/toggles/CharacterRarityToggle.tsx
  libs/zzz/ui/src/toggles/ElementToggle.tsx
  libs/zzz/ui/src/toggles/index.ts
  libs/zzz/ui/src/util/index.tsx
  libs/zzz/util/src/index.ts
  libs/zzz/util/src/level.ts
  tsconfig.base.json
Labels: showDevComponents, ZO

#2697 ZO Wengine page
  apps/zzz-frontend/src/app/App.tsx
  apps/zzz-frontend/src/app/Header.tsx
  libs/zzz/page-wengines/.babelrc
  libs/zzz/page-wengines/.eslintrc.json
  libs/zzz/page-wengines/README.md
  libs/zzz/page-wengines/project.json
  libs/zzz/page-wengines/src/index.tsx
  libs/zzz/page-wengines/tsconfig.eslint.json
  libs/zzz/page-wengines/tsconfig.json
  libs/zzz/page-wengines/tsconfig.lib.json
  tsconfig.base.json
Labels: ZO

#2703 Wengine card
  libs/zzz/assets/src/common/phases/PHASE_1.png
  libs/zzz/assets/src/common/phases/PHASE_2.png
  libs/zzz/assets/src/common/phases/PHASE_3.png
  libs/zzz/assets/src/common/phases/PHASE_4.png
  libs/zzz/assets/src/common/phases/PHASE_5.png
  libs/zzz/assets/src/common/phases/index.ts
  libs/zzz/assets/src/index.ts
  libs/zzz/consts/src/wengine.ts
  libs/zzz/localization/assets/locales/en/wengineNames.json
  libs/zzz/page-wengines/src/index.tsx
  libs/zzz/ui/src/Wengine/WengineCard.tsx
  libs/zzz/ui/src/Wengine/index.ts
Labels: showDevComponents, ZO

#2707 CI: Fix dev flag
  .github/workflows/build-frontend.yml
Labels: CI

#2710 ZO: Update disc editor layout
  libs/zzz/ui/src/Disc/DiscEditor/DiscEditor.tsx
  libs/zzz/ui/src/Disc/DiscEditor/SubstatInput.tsx
  libs/zzz/ui/src/Disc/DiscMainStatDropdown.tsx
  libs/zzz/ui/src/Disc/DiscMainStatGroup.tsx
  libs/zzz/ui/src/Disc/index.tsx
  tsconfig.base.json
Labels: ZO

#2711 ZO: Wengine database manager
  libs/zzz/consts/src/wengine.ts
  libs/zzz/db/src/Database/DataManagers/CharacterDataManager.ts
  libs/zzz/db/src/Database/DataManagers/DiscDataManager.ts
  libs/zzz/db/src/Database/DataManagers/WengineDataManager.ts
  libs/zzz/db/src/Database/Database.ts
  libs/zzz/db/src/Database/exim.ts
  libs/zzz/db/src/Interfaces/IDbDisc.ts
  libs/zzz/db/src/Interfaces/IDbWengine.ts
  libs/zzz/db/src/Interfaces/IZZZChracter.ts
  libs/zzz/db/src/Interfaces/IZZZDatabase.ts
  libs/zzz/db/src/Interfaces/index.ts
  libs/zzz/db/src/driveDiskScanner.ts
  libs/zzz/disc-scanner/src/lib/parse.ts
  libs/zzz/disc-scanner/src/lib/processImg.ts
  libs/zzz/ui/src/Disc/DiscCard.tsx
  libs/zzz/ui/src/Disc/DiscEditor/DiscEditor.tsx
  libs/zzz/ui/src/Disc/DiscEditor/SubstatInput.tsx
  libs/zzz/util/src/disc/discSortUtil.ts
  libs/zzz/zood/.eslintrc.json
  libs/zzz/zood/README.md
  libs/zzz/zood/package.json
  libs/zzz/zood/project.json
  libs/zzz/zood/src/IDisc.ts
  libs/zzz/zood/src/IWengine.ts
  libs/zzz/zood/src/index.ts
  libs/zzz/zood/tsconfig.eslint.json
  libs/zzz/zood/tsconfig.json
  libs/zzz/zood/tsconfig.lib.json
  tsconfig.base.json
Labels: ZO

#2725 ZO: Add a roadmap to home page
  .github/workflows/build-frontend.yml
  .github/workflows/build-new-release.yml
  apps/zzz-frontend/.env
  libs/zzz/page-home/src/Roadmap.tsx
  libs/zzz/page-home/src/index.tsx
Labels: ZO

#2679 GO: Sync traveler level across all elements
  libs/gi/page-team/src/CharProfileCharEditor.tsx
  libs/gi/ui/src/components/character/editor/Content.tsx
Labels: GO

#2727 ZO: Add 4p conditional gates
  libs/zzz/consts/src/disc.ts
Labels: ZO

#2714 ZO: fix some scanner issues upon import
  libs/zzz/db/src/driveDiskScanner.ts
Labels: ZO

#2723 ZO: Wengine filters
  libs/zzz/db-ui/src/hooks/index.ts
  libs/zzz/db-ui/src/hooks/useWengine.ts
  libs/zzz/db/src/Database/DataEntries/DisplayWengineEntry.ts
  libs/zzz/db/src/Database/DataManagers/WengineDataManager.ts
  libs/zzz/db/src/Database/DataManagers/index.ts
  libs/zzz/db/src/Database/Database.ts
  libs/zzz/localization/assets/locales/en/page_wengine.json
  libs/zzz/localization/assets/locales/en/ui.json
  libs/zzz/page-wengines/src/WengineFilter.tsx
  libs/zzz/page-wengines/src/index.tsx
  libs/zzz/ui/src/Character/index.tsx
  libs/zzz/ui/src/Wengine/WengineCard.tsx
  libs/zzz/ui/src/toggles/WengineRarityToggle.tsx
  libs/zzz/ui/src/toggles/WengineToggle.tsx
  libs/zzz/ui/src/toggles/index.ts
  libs/zzz/util/src/index.ts
  libs/zzz/util/src/wengine/index.ts
  libs/zzz/util/src/wengine/wengineSortUtil.ts
Labels: showDevComponents, ZO

#2729 ZO: wengine editor
  apps/zzz-frontend/src/app/Header.tsx
  libs/gi/ui/src/components/weapon/WeaponEditor.tsx
  libs/zzz/assets/src/index.ts
  libs/zzz/consts/src/common.ts
  libs/zzz/db/src/Database/DataEntries/DisplayWengineEntry.ts
  libs/zzz/db/src/Interfaces/index.ts
  libs/zzz/localization/assets/locales/en/page_settings.json
  libs/zzz/localization/assets/locales/en/ui.json
  libs/zzz/page-wengines/src/index.tsx
  libs/zzz/stats/src/wengine.ts
  libs/zzz/ui/src/LevelSelect.tsx
  libs/zzz/ui/src/Settings/DatabaseCard.tsx
  libs/zzz/ui/src/Wengine/PhaseDropdown.tsx
  libs/zzz/ui/src/Wengine/WengineCard.tsx
  libs/zzz/ui/src/Wengine/WengineEditor.tsx
  libs/zzz/ui/src/Wengine/WengineSelectionModal.tsx
  libs/zzz/ui/src/Wengine/WengineSubstatDisplay.tsx
  libs/zzz/ui/src/Wengine/index.ts
  libs/zzz/ui/src/index.tsx
  libs/zzz/util/src/level.ts
Labels: showDevComponents, ZO

#2742 GO: Scroll top whenever the bottom nav is clicked
  libs/gi/page-team/src/CharacterDisplay/Content.tsx
Labels: GO

#2741 ZO: add incremental main stat values
  libs/zzz/consts/src/disc.ts
Labels: ZO

#2753 SRO/ZO: Fix meta generation for dmg instances
  libs/sr/formula/src/data/char/sheets/Firefly.ts
  libs/sr/formula/src/data/char/util.ts
  libs/sr/formula/src/meta.ts
  libs/zzz/formula/src/data/char/util.ts
Labels: SRO, ZO

#2749 ZO: Character Editor
  apps/zzz-frontend/src/app/App.tsx
  libs/zzz/consts/src/common.ts
  libs/zzz/db-ui/src/context/CharacterContext.tsx
  libs/zzz/db-ui/src/context/index.ts
  libs/zzz/db/src/Database/DataManagers/CharacterDataManager.ts
  libs/zzz/db/src/Database/DataManagers/WengineDataManager.ts
  libs/zzz/db/src/Database/exim.ts
  libs/zzz/db/src/Interfaces/IZZZChracter.ts
  libs/zzz/localization/assets/locales/en/charNames_gen.json
  libs/zzz/localization/assets/locales/en/page_characters.json
  libs/zzz/page-characters/src/index.tsx
  libs/zzz/page-optimize/src/CharacterContext.ts
  libs/zzz/page-optimize/src/index.tsx
  libs/zzz/stats/src/char.ts
  libs/zzz/ui/src/Character/CharacterCard.tsx
  libs/zzz/ui/src/Character/CharacterProfilePieces.tsx
  libs/zzz/ui/src/Character/CharacterSelectionModal.tsx
  libs/zzz/ui/src/Character/TalentDropdown.tsx
  libs/zzz/ui/src/Character/card/CharacterCardContent.tsx
  libs/zzz/ui/src/Character/card/CharacterCardStats.tsx
  libs/zzz/ui/src/Character/card/index.ts
  libs/zzz/ui/src/Character/editor/CharacterEditor.tsx
  libs/zzz/ui/src/Character/editor/Content.tsx
  libs/zzz/ui/src/Character/editor/index.tsx
  libs/zzz/ui/src/Character/index.tsx
  libs/zzz/ui/src/Settings/DatabaseCard.tsx
  libs/zzz/util/src/index.ts
  libs/zzz/util/src/talent/index.ts
  libs/zzz/util/src/talent/talent.ts
  libs/zzz/zood/src/ICharacter.ts
  libs/zzz/zood/src/index.ts
Labels: showDevComponents, ZO

#2750 ZO: disc equipment cache
  libs/zzz/db/src/Database/DataManagers/CharacterDataManager.ts
  libs/zzz/db/src/Database/DataManagers/DiscDataManager.ts
  libs/zzz/db/src/Database/Database.ts
  libs/zzz/db/src/Interfaces/IZZZChracter.ts
Labels: ZO

#2692 Pando: Add pruning
  libs/pando/engine/src/index.ts
  libs/pando/engine/src/node/index.ts
  libs/pando/engine/src/node/transform.spec.ts
  libs/pando/engine/src/node/transform.ts
  libs/pando/engine/src/optimization/index.ts
  libs/pando/engine/src/optimization/prune.spec.ts
  libs/pando/engine/src/optimization/prune.ts
  libs/pando/engine/src/optimization/simplify.spec.ts
  libs/pando/engine/src/optimization/simplify.ts
Labels: Pando

#2762 ZO: minor refactor
  libs/zzz/assets/src/index.ts
  libs/zzz/consts/src/character.ts
  libs/zzz/consts/src/common.ts
  libs/zzz/consts/src/disc.ts
  libs/zzz/consts/src/wengine.ts
  libs/zzz/db-ui/src/context/CharacterContext.ts
  libs/zzz/db-ui/src/context/CharacterContext.tsx
  libs/zzz/db/src/Database/DataManagers/CharacterDataManager.ts
  libs/zzz/db/src/Database/DataManagers/WengineDataManager.ts
  libs/zzz/db/src/Interfaces/IDbDisc.ts
  libs/zzz/formula/src/data/util/listing.ts
  libs/zzz/formula/src/util.ts
  libs/zzz/localization/assets/locales/en/page_characters.json
  libs/zzz/page-optimize/src/BuildDisplay.tsx
  libs/zzz/page-optimize/src/ConditionalToggle.tsx
  libs/zzz/page-optimize/src/DiscConditionalCard.tsx
  libs/zzz/page-optimize/src/Optimize.tsx
  libs/zzz/page-optimize/src/SetFilter.tsx
  libs/zzz/page-optimize/src/index.tsx
  libs/zzz/ui/src/Character/CharacterCard.tsx
  libs/zzz/ui/src/Character/CharacterProfilePieces.tsx
  libs/zzz/ui/src/Character/CharacterSelectionModal.tsx
  libs/zzz/ui/src/Character/CoreDropdown.tsx
  libs/zzz/ui/src/Character/SkillDropdown.tsx
  libs/zzz/ui/src/Character/TalentDropdown.tsx
  libs/zzz/ui/src/Character/card/CharacterCardContent.tsx
  libs/zzz/ui/src/Character/editor/CharacterEditor.tsx
  libs/zzz/ui/src/Character/editor/Content.tsx
  libs/zzz/ui/src/Character/index.tsx
  libs/zzz/ui/src/LevelSelect.tsx
  libs/zzz/ui/src/Wengine/WengineCard.tsx
  libs/zzz/ui/src/Wengine/WengineEditor.tsx
  libs/zzz/util/src/index.ts
  libs/zzz/util/src/level.ts
  libs/zzz/util/src/talent/index.ts
  libs/zzz/util/src/talent/talent.ts
  libs/zzz/util/src/wengine/wengineSortUtil.ts
  libs/zzz/zood/src/ICharacter.ts
  libs/zzz/zood/src/IWengine.ts
Labels: showDevComponents, ZO

#2764 ZO: Fix issue with editor crashing when selecting disc substats
  libs/zzz/ui/src/Disc/DiscEditor/SubstatInput.tsx
Labels: ZO

#2765 ZO: Fix disc sub editor range
  libs/zzz/ui/src/Disc/DiscEditor/SubstatInput.tsx
Labels: ZO

#2748 ZO: add links & credits to home page
  apps/zzz-frontend/.env
  libs/zzz/localization/assets/locales/en/page_home.json
  libs/zzz/page-home/src/IntroCard.tsx
  libs/zzz/page-home/src/QuickLinksCard.tsx
  libs/zzz/page-home/src/Roadmap.tsx
  libs/zzz/page-home/src/TeamCard.tsx
  libs/zzz/page-home/src/index.tsx
  libs/zzz/page-home/src/teamIcons/failchon.png
  libs/zzz/page-home/src/teamIcons/frzyc.png
  libs/zzz/page-home/src/teamIcons/lantua.png
  libs/zzz/page-home/src/teamIcons/lunik.png
  libs/zzz/page-home/src/teamIcons/van.webp
Labels: ZO

#2763 ZO: Disc equipment on character
  libs/zzz/localization/assets/locales/en/disc.json
  libs/zzz/localization/assets/locales/en/page_characters.json
  libs/zzz/ui/src/Character/CoreDropdown.tsx
  libs/zzz/ui/src/Character/EquippedGrid.tsx
  libs/zzz/ui/src/Character/editor/Content.tsx
  libs/zzz/ui/src/Character/index.tsx
  libs/zzz/ui/src/Disc/DiscEditor/DiscEditor.tsx
Labels: showDevComponents, ZO

#2766 Pando: Pruning 2: Electric Boogaloo
  libs/pando/engine/src/debug.ts
  libs/pando/engine/src/optimization/prune.spec.ts
  libs/pando/engine/src/optimization/prune.ts
Labels: Pando

#2719 ZO: pando disc sheets
  libs/zzz/formula/README.md
  libs/zzz/formula/src/data/disc/disc.test.ts
  libs/zzz/formula/src/data/disc/index.ts
  libs/zzz/formula/src/data/disc/sheets/AstralVoice.ts
  libs/zzz/formula/src/data/disc/sheets/BranchBladeSong.ts
  libs/zzz/formula/src/data/disc/sheets/ChaosJazz.ts
  libs/zzz/formula/src/data/disc/sheets/ChaoticMetal.ts
  libs/zzz/formula/src/data/disc/sheets/FangedMetal.ts
  libs/zzz/formula/src/data/disc/sheets/FreedomBlues.ts
  libs/zzz/formula/src/data/disc/sheets/HormonePunk.ts
  libs/zzz/formula/src/data/disc/sheets/InfernoMetal.ts
  libs/zzz/formula/src/data/disc/sheets/PolarMetal.ts
  libs/zzz/formula/src/data/disc/sheets/ProtoPunk.ts
  libs/zzz/formula/src/data/disc/sheets/PufferElectro.ts
  libs/zzz/formula/src/data/disc/sheets/ShockstarDisco.ts
  libs/zzz/formula/src/data/disc/sheets/SoulRock.ts
  libs/zzz/formula/src/data/disc/sheets/SwingJazz.ts
  libs/zzz/formula/src/data/disc/sheets/ThunderMetal.ts
  libs/zzz/formula/src/data/disc/sheets/WoodpeckerElectro.ts
  libs/zzz/formula/src/data/util/listing.ts
  libs/zzz/formula/src/data/util/read.ts
  libs/zzz/formula/src/data/util/sheet.ts
  libs/zzz/formula/src/formula.test.ts
  libs/zzz/formula/src/gen-sheet/all-generator.ts
  libs/zzz/formula/src/gen-sheet/disc/__sheet__.ts.template
  libs/zzz/formula/src/generators/gen-sheet/all-generator.ts
  libs/zzz/formula/src/generators/gen-sheet/all-schema.json
  libs/zzz/formula/src/generators/gen-sheet/char/__sheet__.ts.template
  libs/zzz/formula/src/generators/gen-sheet/disc/__sheet__.ts.template
  libs/zzz/formula/src/generators/gen-sheet/genIndex.ts
  libs/zzz/formula/src/generators/gen-sheet/genSheet.ts
  libs/zzz/formula/src/generators/gen-sheet/schema.d.ts
  libs/zzz/formula/src/generators/gen-sheet/single-generator.ts
  libs/zzz/formula/src/generators/gen-sheet/single-schema.json
  libs/zzz/formula/src/generators/gen-sheet/wengine/__sheet__.ts.template
  libs/zzz/formula/src/meta.ts
Labels: ZO

#2662 SRO: Initial Seele sheet implementation
  libs/sr/formula-ui/src/char/sheets/Seele.tsx
  libs/sr/formula/src/data/char/sheets/Seele.ts
  libs/sr/formula/src/meta.ts
  libs/sr/stats/src/mappedStats/char/maps/Seele.ts
Labels: SRO

#2770 ZO: Disc swap functionality
  libs/zzz/localization/assets/locales/en/page_characters.json
  libs/zzz/ui/src/Character/EquippedGrid.tsx
  libs/zzz/ui/src/Character/editor/Content.tsx
  libs/zzz/ui/src/Disc/DiscCard.tsx
  libs/zzz/ui/src/Disc/DiscEditor/DiscEditor.tsx
  libs/zzz/ui/src/Disc/DiscSwapModal.tsx
  libs/zzz/ui/src/Disc/index.tsx
Labels: showDevComponents, ZO

#2776 ZO: Improve zzz-formula accuracy to in-game mechanics
  libs/zzz/consts/src/character.ts
  libs/zzz/dm/src/dm/character/character.ts
  libs/zzz/dm/src/dm/character/consts.ts
  libs/zzz/formula/src/data/char/util.ts
  libs/zzz/formula/src/data/common/dmg.ts
  libs/zzz/formula/src/data/common/index.ts
  libs/zzz/formula/src/data/disc/disc.test.ts
  libs/zzz/formula/src/data/disc/sheets/ChaosJazz.ts
  libs/zzz/formula/src/data/disc/sheets/PolarMetal.ts
  libs/zzz/formula/src/data/disc/sheets/ShockstarDisco.ts
  libs/zzz/formula/src/data/util/listing.ts
  libs/zzz/formula/src/data/util/read.ts
  libs/zzz/formula/src/data/util/tag.ts
  libs/zzz/formula/src/executors/gen-desc/executor.ts
  libs/zzz/formula/src/formula.test.ts
  libs/zzz/formula/src/meta.ts
  libs/zzz/stats/Data/Characters/Anby.json
  libs/zzz/stats/Data/Characters/Anton.json
  libs/zzz/stats/Data/Characters/Astra.json
  libs/zzz/stats/Data/Characters/Ben.json
  libs/zzz/stats/Data/Characters/Billy.json
  libs/zzz/stats/Data/Characters/Burnice.json
  libs/zzz/stats/Data/Characters/Caesar.json
  libs/zzz/stats/Data/Characters/Corin.json
  libs/zzz/stats/Data/Characters/Ellen.json
  libs/zzz/stats/Data/Characters/Evelyn.json
  libs/zzz/stats/Data/Characters/Grace.json
  libs/zzz/stats/Data/Characters/Harumasa.json
  libs/zzz/stats/Data/Characters/Jane.json
  libs/zzz/stats/Data/Characters/Koleda.json
  libs/zzz/stats/Data/Characters/Lighter.json
  libs/zzz/stats/Data/Characters/Lucy.json
  libs/zzz/stats/Data/Characters/Lycaon.json
  libs/zzz/stats/Data/Characters/Miyabi.json
  libs/zzz/stats/Data/Characters/Nekomata.json
  libs/zzz/stats/Data/Characters/Nicole.json
  libs/zzz/stats/Data/Characters/Piper.json
  libs/zzz/stats/Data/Characters/QingYi.json
  libs/zzz/stats/Data/Characters/Rina.json
  libs/zzz/stats/Data/Characters/Seth.json
  libs/zzz/stats/Data/Characters/Soldier11.json
  libs/zzz/stats/Data/Characters/Soukaku.json
  libs/zzz/stats/Data/Characters/Yanagi.json
  libs/zzz/stats/Data/Characters/ZhuYuan.json
  libs/zzz/stats/src/allStat_gen.json
Labels: ZO

#2784 ZO: minor update to BranchBladeSong disc sheet
  libs/zzz/formula/src/data/disc/sheets/BranchBladeSong.ts
Labels: ZO

#2778 SRO: Add pruning again to SRO
  libs/sr/solver/src/childWorker.ts
  libs/sr/solver/src/common.ts
  libs/sr/solver/src/parentWorker.ts
  libs/sr/solver/src/solver.ts
  libs/sr/solver/tsconfig.json
Labels: SRO

#2794 ZO: add buff conds
  libs/zzz/formula/src/data/disc/sheets/AstralVoice.ts
  libs/zzz/formula/src/data/disc/sheets/BranchBladeSong.ts
  libs/zzz/formula/src/data/disc/sheets/ChaosJazz.ts
  libs/zzz/formula/src/data/disc/sheets/ChaoticMetal.ts
  libs/zzz/formula/src/data/disc/sheets/FangedMetal.ts
  libs/zzz/formula/src/data/disc/sheets/HormonePunk.ts
  libs/zzz/formula/src/data/disc/sheets/InfernoMetal.ts
  libs/zzz/formula/src/data/disc/sheets/PolarMetal.ts
  libs/zzz/formula/src/data/disc/sheets/ProtoPunk.ts
  libs/zzz/formula/src/data/disc/sheets/PufferElectro.ts
  libs/zzz/formula/src/data/disc/sheets/ShockstarDisco.ts
  libs/zzz/formula/src/data/disc/sheets/SwingJazz.ts
  libs/zzz/formula/src/data/disc/sheets/ThunderMetal.ts
  libs/zzz/formula/src/data/disc/sheets/WoodpeckerElectro.ts
  libs/zzz/formula/src/generators/gen-sheet/disc/__sheet__.ts.template
Labels: ZO

#2791 ZO: add zzz-solver-pando
  libs/zzz/solver-pando/.eslintrc.json
  libs/zzz/solver-pando/README.md
  libs/zzz/solver-pando/jest.config.ts
  libs/zzz/solver-pando/project.json
  libs/zzz/solver-pando/src/childWorker.ts
  libs/zzz/solver-pando/src/index.ts
  libs/zzz/solver-pando/src/parentWorker.ts
  libs/zzz/solver-pando/src/solver.ts
  libs/zzz/solver-pando/tsconfig.eslint.json
  libs/zzz/solver-pando/tsconfig.json
  libs/zzz/solver-pando/tsconfig.lib.json
  libs/zzz/solver-pando/tsconfig.spec.json
  libs/zzz/solver-pando/vite.config.ts
  tsconfig.base.json
Labels: ZO

#2798 Pando: Add `pruneBottom` and update `reaffine` keys
  libs/pando/engine/src/optimization/prune.spec.ts
  libs/pando/engine/src/optimization/prune.ts
  libs/pando/engine/src/tag/keys.ts
Labels: Pando

#2787 ZO: Allow any usage of wengine on any char, fix disc location default…
  libs/zzz/db/src/Database/DataManagers/CharMetaDataManager.ts
  libs/zzz/db/src/Database/DataManagers/DiscDataManager.ts
  libs/zzz/db/src/Database/DataManagers/index.ts
  libs/zzz/db/src/Database/Database.ts
  libs/zzz/db/src/Interfaces/IZZZChracter.ts
  libs/zzz/page-optimize/src/BaseStatCard.tsx
  libs/zzz/page-optimize/src/index.tsx
  libs/zzz/ui/src/Wengine/WengineCard.tsx
  libs/zzz/ui/src/Wengine/WengineSelectionModal.tsx
  libs/zzz/ui/src/Wengine/WengineSwapModal.tsx
Labels: showDevComponents, ZO

#2780 ZO: fix crash on import due to dup detection
  libs/zzz/db/src/Database/DataManagers/DiscDataManager.ts
Labels: fix ASAP, ZO

#2801 ZO: Add GA
  .github/workflows/build-frontend.yml
  apps/frontend/src/main.tsx
  apps/zzz-frontend/src/main.tsx
Labels: ZO

#2804 ZO: add scanner info, improve scanning
  libs/common/img-util/src/processing.ts
  libs/zzz/db/src/Database/DataManagers/DiscDataManager.ts
  libs/zzz/ui/src/Disc/DiscEditor/DiscEditor.tsx
  libs/zzz/ui/src/Disc/DiscEditor/ScanInfoModal.tsx
  libs/zzz/ui/src/Disc/DiscEditor/card-sc.png
  libs/zzz/ui/src/Disc/DiscEditor/full-sc.png
Labels: ZO

#2805 SRO: Update to use common_dmg_ for AllDamage
  libs/sr/consts/src/common.ts
  libs/sr/dm/src/mapping/common.ts
  libs/sr/stats/Data/LightCone/ASecretVow.json
  libs/sr/stats/Data/LightCone/PatienceIsAllYouNeed.json
  libs/sr/stats/Data/LightCone/TheSeriousnessOfBreakfast.json
  libs/sr/stats/src/allStat_gen.json
  libs/sr/stats/src/executors/gen-stats/src/lightConeData.ts
  libs/sr/stats/src/executors/gen-stats/src/relicData.ts
Labels: SRO

#2810 SRO: Fix crash on sro
  libs/sr/formula-ui/src/char/CharBase.tsx
  libs/sr/formula/src/data/util/read.ts
Labels: SRO

#2809 ZO: Improved character profile on m4 optimize page
  libs/zzz/assets/src/common/faction/IconCampBelobogIndustries.png
  libs/zzz/assets/src/common/faction/IconCampGentleHouse.png
  libs/zzz/assets/src/common/faction/IconCampH.S.O-S6.png
  libs/zzz/assets/src/common/faction/IconCampJaneBadge.png
  libs/zzz/assets/src/common/faction/IconCampN.E.P.S..png
  libs/zzz/assets/src/common/faction/IconCampObols.png
  libs/zzz/assets/src/common/faction/IconCampRandomPlay.png
  libs/zzz/assets/src/common/faction/IconCampSonsOfCalydon.png
  libs/zzz/assets/src/common/faction/IconCampStarsOfLyra.png
  libs/zzz/assets/src/common/faction/IconCampVictoriaHousekeepingCo.png
  libs/zzz/assets/src/common/faction/index.ts
  libs/zzz/assets/src/index.ts
  libs/zzz/dm/src/dm/character/character.ts
  libs/zzz/page-optimize-pando/src/CharacterOptDisplay.tsx
  libs/zzz/stats/Data/Characters/Anby.json
  libs/zzz/stats/Data/Characters/Anton.json
  libs/zzz/stats/Data/Characters/Astra.json
  libs/zzz/stats/Data/Characters/Ben.json
  libs/zzz/stats/Data/Characters/Billy.json
  libs/zzz/stats/Data/Characters/Burnice.json
  libs/zzz/stats/Data/Characters/Caesar.json
  libs/zzz/stats/Data/Characters/Corin.json
  libs/zzz/stats/Data/Characters/Ellen.json
  libs/zzz/stats/Data/Characters/Evelyn.json
  libs/zzz/stats/Data/Characters/Grace.json
  libs/zzz/stats/Data/Characters/Harumasa.json
  libs/zzz/stats/Data/Characters/Jane.json
  libs/zzz/stats/Data/Characters/Koleda.json
  libs/zzz/stats/Data/Characters/Lighter.json
  libs/zzz/stats/Data/Characters/Lucy.json
  libs/zzz/stats/Data/Characters/Lycaon.json
  libs/zzz/stats/Data/Characters/Miyabi.json
  libs/zzz/stats/Data/Characters/Nekomata.json
  libs/zzz/stats/Data/Characters/Nicole.json
  libs/zzz/stats/Data/Characters/Piper.json
  libs/zzz/stats/Data/Characters/QingYi.json
  libs/zzz/stats/Data/Characters/Rina.json
  libs/zzz/stats/Data/Characters/Seth.json
  libs/zzz/stats/Data/Characters/Soldier11.json
  libs/zzz/stats/Data/Characters/Soukaku.json
  libs/zzz/stats/Data/Characters/Yanagi.json
  libs/zzz/stats/Data/Characters/ZhuYuan.json
  libs/zzz/stats/src/allStat_gen.json
  libs/zzz/ui/src/Character/CharacterProfilePieces.tsx
Labels: showDevComponents, ZO

#2807 Add `deduplicate`
  libs/game-opt/solver/src/parentWorker.ts
  libs/gi/formula/src/example.test.ts
  libs/pando/engine/src/optimization/index.ts
  libs/pando/engine/src/optimization/prune.ts
  libs/pando/engine/src/optimization/simplify.spec.ts
  libs/pando/engine/src/optimization/simplify.ts
  libs/pando/engine/src/util/arrayMap.ts
  libs/pando/engine/src/util/index.ts
Labels: Pando

#2808 Pando: Add `compileDiff`
  libs/pando/engine/src/node/transform.spec.ts
  libs/pando/engine/src/node/transform.ts
  libs/pando/engine/src/optimization/prune.ts
  libs/pando/engine/src/util/custom.ts
Labels: Pando

#2811 Update GameOpt typing
  apps/gi-frontend/src/app/teams/[teamId]/CalcWrapper.tsx
  libs/game-opt/engine/src/IConditionalData.ts
  libs/game-opt/engine/src/calculator.ts
  libs/game-opt/engine/src/read.ts
  libs/game-opt/engine/src/tag.ts
  libs/game-opt/formula-ui/src/DebugDisplay.tsx
  libs/game-opt/formula-ui/src/context/CalcContext.ts
  libs/game-opt/formula-ui/src/context/TagContext.ts
  libs/game-opt/formula-ui/src/index.ts
  libs/game-opt/formula-ui/src/types/debug.ts
  libs/game-opt/formula-ui/src/types/index.ts
  libs/game-opt/formula/src/metadata.ts
  libs/game-opt/formula/src/util.ts
  libs/game-opt/sheet-ui/src/types/conditional.ts
  libs/gi/formula/src/calculator.ts
  libs/gi/formula/src/data/artifact/util.ts
  libs/gi/formula/src/data/util/read.ts
  libs/gi/formula/src/data/util/tag.ts
  libs/gi/formula/src/data/util/tagMapType.ts
  libs/sr/formula/src/calculator.ts
  libs/sr/formula/src/data/lightCone/util.ts
  libs/sr/formula/src/data/relic/util.ts
  libs/sr/formula/src/data/util/index.ts
  libs/sr/formula/src/data/util/read.ts
  libs/sr/formula/src/data/util/tag.ts
  libs/zzz/formula/src/calculator.ts
  libs/zzz/formula/src/data/disc/util.ts
  libs/zzz/formula/src/data/util/index.ts
  libs/zzz/formula/src/data/util/read.ts
  libs/zzz/formula/src/data/util/tag.ts
  libs/zzz/formula/src/data/wengine/util.ts
  libs/zzz/page-optimize-pando/src/BonusStats.tsx
Labels: game-opt
