Repository frzyc/genshin-optimizer, pull requests merged in 2025-06, with the labels that each got.

#2981 ZO: Fix Yunkui Tales 4p and missing skill image
  libs/zzz/assets/src/common/skill/IconRoleSkillKeySpecialV3_02.png
  libs/zzz/assets/src/common/skill/index.ts
  libs/zzz/formula/src/data/disc/sheets/YunkuiTales.ts
  libs/zzz/i18n/src/Translate.tsx
Labels: ZO

#2991 GO: fix useEffect freeze
  libs/gi/page-team/src/CharacterDisplay/Tabs/TabOptimize/Components/UseEquipped.tsx
Labels: fix ASAP, GO

#2996 GO: Invert how Skirk C2 applies ATK so stats page matches, and change C6 getting buffed by Burst
  libs/gi/localization/assets/locales/en/char_Skirk.json
  libs/gi/sheets/src/Characters/Skirk/index.tsx
Labels: GO

#2983 ZO: More character sheets
  libs/zzz/consts/src/common.ts
  libs/zzz/formula-ui/src/char/CharBase.tsx
  libs/zzz/formula-ui/src/char/CharStatsDisplay.tsx
  libs/zzz/formula-ui/src/char/sheets/Jane.tsx
  libs/zzz/formula-ui/src/char/sheets/Lighter.tsx
  libs/zzz/formula-ui/src/char/sheets/Qingyi.tsx
  libs/zzz/formula-ui/src/char/sheets/Soldier0Anby.tsx
  libs/zzz/formula/src/data/char/sheets/Jane.ts
  libs/zzz/formula/src/data/char/sheets/Lighter.ts
  libs/zzz/formula/src/data/char/sheets/Qingyi.ts
  libs/zzz/formula/src/data/char/sheets/Soldier0Anby.ts
  libs/zzz/formula/src/data/common/dmg.ts
  libs/zzz/formula/src/data/common/index.ts
  libs/zzz/formula/src/data/common/prep.ts
  libs/zzz/formula/src/data/util/listing.ts
  libs/zzz/formula/src/data/util/tag.ts
  libs/zzz/formula/src/meta.ts
  libs/zzz/localization/assets/locales/en/char_Jane.json
  libs/zzz/localization/assets/locales/en/char_Lighter.json
  libs/zzz/localization/assets/locales/en/char_Qingyi.json
  libs/zzz/localization/assets/locales/en/char_Soldier0Anby.json
  libs/zzz/page-optimize/src/CharSheetsDisplay.tsx
  libs/zzz/stats/Data/Characters/Soldier0Anby.json
  libs/zzz/stats/src/allStat_gen.json
  libs/zzz/stats/src/executors/gen-stats/src/characterData.ts
  libs/zzz/stats/src/mappedStats/char/maps/Jane.ts
  libs/zzz/stats/src/mappedStats/char/maps/Lighter.ts
  libs/zzz/stats/src/mappedStats/char/maps/Qingyi.ts
  libs/zzz/stats/src/mappedStats/char/maps/Soldier0Anby.ts
Labels: showDevComponents

#3002 ZO: Change how mv_mult_ is applied
  libs/zzz/formula/src/data/char/sheets/Evelyn.ts
  libs/zzz/formula/src/data/char/util.ts
Labels: showDevComponents
