Repository frzyc/genshin-optimizer, pull requests merged in 2025-04, with the labels that each got.

#2931 ZO: Fix misc. solver issues
  libs/zzz/page-optimize/src/Optimize/index.tsx
  libs/zzz/solver/src/index.ts
Labels: ZO

#2930 ZO: Add debug for solver
  libs/zzz/page-optimize/src/Optimize/index.tsx
  libs/zzz/solver/src/index.ts
Labels: ZO

#2932 ZO: Bonus stat improvements
  libs/zzz/db/src/Database/DataManagers/CharacterOptManager.ts
  libs/zzz/page-optimize/src/BonusStats.tsx
  libs/zzz/page-optimize/src/CharCalcProvider.tsx
Labels: ZO

#2934 CI: Update release pipelines for simultaneous release/versions
  .github/workflows/build-frontend.yml
  .github/workflows/build-new-release.yml
  .github/workflows/build-zo-release.yml
  .github/workflows/deploy-frontend.yml
  .github/workflows/new-zo-release.yml
  apps/zzz-frontend/package.json
Labels: CI

#2943 ZO: Fix wengine optimization when wengine isn't equipped
  apps/zzz-frontend/vite.config.mts
  libs/zzz/formula-ui/src/char/CharCalcProvider.tsx
  libs/zzz/formula/src/data/wengine/wengine.test.ts
  libs/zzz/formula/src/formula.test.ts
  libs/zzz/formula/src/util.ts
Labels: ZO

#2949 CI: Add version to run name for clarity on releases
  .github/workflows/ci.yml
  .github/workflows/new-release.yml
  .github/workflows/new-zo-release.yml
Labels: CI

#2951 GO: add lootbar ad/banner
  libs/gi/page-home/src/QuickLinksCard.tsx
  libs/gi/page-home/src/index.tsx
  libs/gi/ui/src/assets/index.ts
  libs/gi/ui/src/assets/lootbar.png
  libs/gi/ui/src/components/ad/AdButtons.tsx
  libs/gi/ui/src/components/ad/AdWrapper.tsx
  libs/gi/ui/src/components/ad/GoAd/GODevAd.tsx
  libs/gi/ui/src/components/ad/GoAd/LootbarAd.tsx
  libs/gi/ui/src/components/ad/GoAd/SRODevAd.tsx
  libs/gi/ui/src/components/ad/index.ts
  libs/gi/ui/src/components/ad/util.tsx
  libs/gi/ui/src/index.ts
Labels: GO
