Repository frzyc/genshin-optimizer, pull requests merged in 2025-01, with the labels that each got.

#2598 ZO disc scanner
  libs/common/img-util/src/processing.ts
  libs/zzz/consts/src/disc.ts
  libs/zzz/db/src/Database/DataManagers/DiscDataManager.ts
  libs/zzz/db/src/Interfaces/IDbDisc.ts
  libs/zzz/db/src/Interfaces/IDisc.ts
  libs/zzz/disc-scanner/.babelrc
  libs/zzz/disc-scanner/.eslintrc.json
  libs/zzz/disc-scanner/README.md
  libs/zzz/disc-scanner/project.json
  libs/zzz/disc-scanner/src/index.ts
  libs/zzz/disc-scanner/src/lib/ScanningQueue.tsx
  libs/zzz/disc-scanner/src/lib/consts.ts
  libs/zzz/disc-scanner/src/lib/enStringMap.ts
  libs/zzz/disc-scanner/src/lib/parse.ts
  libs/zzz/disc-scanner/src/lib/processImg.ts
  libs/zzz/disc-scanner/tsconfig.eslint.json
  libs/zzz/disc-scanner/tsconfig.json
  libs/zzz/disc-scanner/tsconfig.lib.json
  libs/zzz/page-discs/src/index.tsx
  libs/zzz/solver/src/common.ts
  libs/zzz/ui/src/Disc/DiscCard.tsx
  libs/zzz/ui/src/Disc/DiscEditor/DiscEditor.tsx
  libs/zzz/ui/src/Disc/DiscEditor/ScanningUtil.tsx
  libs/zzz/ui/src/Disc/DiscEditor/SubstatInput.tsx
  libs/zzz/ui/src/Disc/DiscMainStatDropdown.tsx
  libs/zzz/ui/src/util/isDev.ts
  tsconfig.base.json
Labels: ZO

#2603 adding basic opt targets to ZO, wrapping up MVPish
  apps/zzz-frontend/index.html
  apps/zzz-frontend/src/app/PageHome.tsx
  libs/common/database/src/lib/DataEntryBase.ts
  libs/gi/db/src/Database/DataEntries/DBMetaEntry.ts
  libs/gi/db/src/Database/DataEntry.ts
  libs/sr/db/src/Database/DataEntries/DBMetaEntry.ts
  libs/sr/db/src/Database/DataEntry.ts
  libs/zzz/consts/src/character.ts
  libs/zzz/consts/src/common.ts
  libs/zzz/consts/src/disc.ts
  libs/zzz/consts/src/index.ts
  libs/zzz/db-ui/src/context/CharacterContext.ts
  libs/zzz/db-ui/src/context/index.ts
  libs/zzz/db/src/Database/DataEntries/DBMetaEntry.ts
  libs/zzz/db/src/Database/DataEntry.test.ts
  libs/zzz/db/src/Database/DataEntry.ts
  libs/zzz/db/src/Database/DataManagers/DiscDataManager.ts
  libs/zzz/db/src/Database/Database.ts
  libs/zzz/db/src/Database/migrate.ts
  libs/zzz/db/src/Interfaces/IDisc.ts
  libs/zzz/disc-scanner/src/lib/enStringMap.ts
  libs/zzz/page-optimize/src/BaseStatCard.tsx
  libs/zzz/page-optimize/src/BuildsDisplay.tsx
  libs/zzz/page-optimize/src/Optimize.tsx
  libs/zzz/page-optimize/src/StatFilterCard.tsx
  libs/zzz/page-optimize/src/index.tsx
  libs/zzz/solver/src/calc.ts
  libs/zzz/solver/src/childWorker.ts
  libs/zzz/solver/src/parentWorker.ts
  libs/zzz/solver/src/solver.ts
  libs/zzz/ui/src/Character/LocationAutocomplete.tsx
  libs/zzz/ui/src/Character/LocationName.tsx
  libs/zzz/ui/src/Character/StatDisplay.tsx
  libs/zzz/ui/src/Character/index.tsx
  libs/zzz/ui/src/Disc/DiscCard.tsx
  libs/zzz/ui/src/Disc/DiscEditor/DiscEditor.tsx
  libs/zzz/ui/src/Settings/UploadCard.tsx
Labels: ZO

#2616 ZO move target selector
  libs/zzz/page-optimize/src/BaseStatCard.tsx
  libs/zzz/page-optimize/src/Optimize.tsx
  libs/zzz/page-optimize/src/OptimizeTargetSelector.tsx
  libs/zzz/page-optimize/src/index.tsx
Labels: ZO

#2621 ZO Add option to clear 4/2p set
  libs/zzz/page-optimize/src/Optimize.tsx
Labels: ZO

#2628 ZO minor fixes
  libs/sr/solver/src/parentWorker.ts
  libs/zzz/page-optimize/src/WorkerSelector.tsx
  libs/zzz/solver/src/parentWorker.ts
Labels: SRO, ZO

#2638 ZO fix crash on specific core levels
  libs/zzz/stats/src/char.ts
Labels: ZO

#2639 ZO minor updates
  apps/zzz-frontend/src/app/Header.tsx
  libs/zzz/consts/src/common.ts
  libs/zzz/db/src/Database/DataManagers/CharacterDataManager.ts
  libs/zzz/disc-scanner/src/lib/parse.ts
  libs/zzz/disc-scanner/src/lib/processImg.ts
  libs/zzz/page-optimize/src/BaseStatCard.tsx
  libs/zzz/page-optimize/src/BuildsDisplay.tsx
  libs/zzz/page-optimize/src/Optimize.tsx
  libs/zzz/solver/src/calc.ts
  libs/zzz/solver/src/common.ts
  libs/zzz/stats/src/wengine.ts
  libs/zzz/ui/src/Disc/DiscEditor/DiscEditor.tsx
Labels: ZO

#2641 ZO Convert disc data from ZZZ-Drive-Disk-Scanner
  libs/common/util/src/lib/object.ts
  libs/zzz/consts/src/disc.ts
  libs/zzz/db/src/driveDiskScanner.ts
  libs/zzz/db/src/index.ts
  libs/zzz/dm/src/dm/disc/discIdMap.json
  libs/zzz/dm/src/dm/disc/discKeys.json
  libs/zzz/dm/src/dm/disc/discNames.json
  libs/zzz/dm/src/dm/disc/discs.ts
  libs/zzz/dm/src/dm/disc/index.ts
  libs/zzz/dm/src/dm/index.ts
  libs/zzz/ui/src/Settings/UploadCard.tsx
Labels: ZO

#2645 fix scanner substat detection
  libs/zzz/db/src/driveDiskScanner.ts
Labels: ZO

#2604 SRO Add conditional search/filter for relic sets/lightcones
  libs/sr/consts/src/lightCone.ts
  libs/sr/consts/src/relic.ts
  libs/sr/page-team/src/LightConeSheetsDisplay.tsx
  libs/sr/page-team/src/RelicSheetsDisplay.tsx
  libs/sr/ui/src/LightCone/LightConeAutocomplete.tsx
  libs/sr/ui/src/LightCone/LightConeEditor/LightConeEditorCard.tsx
Labels: SRO

#2647 ZO: Translation system
  apps/zzz-frontend/project.json
  apps/zzz-frontend/src/app/App.tsx
  apps/zzz-frontend/vite.config.mts
  libs/common/localization/src/executors/gen-locale/executor.ts
  libs/zzz/i18n-node/.eslintrc.json
  libs/zzz/i18n-node/README.md
  libs/zzz/i18n-node/project.json
  libs/zzz/i18n-node/src/i18n.ts
  libs/zzz/i18n-node/src/index.ts
  libs/zzz/i18n-node/tsconfig.eslint.json
  libs/zzz/i18n-node/tsconfig.json
  libs/zzz/i18n-node/tsconfig.lib.json
  libs/zzz/i18n/.babelrc
  libs/zzz/i18n/.eslintrc.json
  libs/zzz/i18n/README.md
  libs/zzz/i18n/project.json
  libs/zzz/i18n/src/Translate.tsx
  libs/zzz/i18n/src/i18n.ts
  libs/zzz/i18n/src/index.ts
  libs/zzz/i18n/tsconfig.eslint.json
  libs/zzz/i18n/tsconfig.json
  libs/zzz/i18n/tsconfig.lib.json
  libs/zzz/localization/.babelrc
  libs/zzz/localization/.eslintrc.json
  libs/zzz/localization/README.md
  libs/zzz/localization/assets/locales/en/disc.json
  libs/zzz/localization/assets/locales/en/header.json
  libs/zzz/localization/assets/locales/en/page_settings.json
  libs/zzz/localization/assets/locales/en/ui.json
  libs/zzz/localization/project.json
  libs/zzz/localization/src/index.ts
  libs/zzz/localization/tsconfig.eslint.json
  libs/zzz/localization/tsconfig.json
  libs/zzz/localization/tsconfig.lib.json
  libs/zzz/theme/.babelrc
  libs/zzz/theme/.eslintrc.json
  libs/zzz/theme/README.md
  libs/zzz/theme/project.json
  libs/zzz/theme/src/Theme.tsx
  libs/zzz/theme/src/index.ts
  libs/zzz/theme/tsconfig.eslint.json
  libs/zzz/theme/tsconfig.json
  libs/zzz/theme/tsconfig.lib.json
  libs/zzz/ui/src/Disc/DiscTrans.tsx
  tsconfig.base.json
Labels: ZO

#2655 ZO fix 2p effect
  libs/zzz/consts/src/disc.ts
  libs/zzz/page-optimize/src/Optimize.tsx
  libs/zzz/page-optimize/src/index.tsx
Labels: ZO

#2643 ZO: Partial implementation of disc filters
  libs/common/database-ui/src/hooks/useDataEntryBase.tsx
  libs/zzz/db-ui/src/hooks/index.ts
  libs/zzz/db-ui/src/hooks/useDiscDisplay.ts
  libs/zzz/db/src/Database/DataEntries/DisplayDiscEntry.ts
  libs/zzz/db/src/Database/Database.ts
  libs/zzz/localization/assets/locales/en/disc.json
  libs/zzz/localization/assets/locales/en/discNames_gen.json
  libs/zzz/localization/assets/locales/en/statKey_gen.json
  libs/zzz/localization/assets/locales/en/ui.json
  libs/zzz/stats/src/index.ts
  libs/zzz/svgicons/src/components/ElementIcon.tsx
  libs/zzz/ui/src/Character/CharIconSideElement.tsx
  libs/zzz/ui/src/Character/LocationFilterMultiAutocomplete.tsx
  libs/zzz/ui/src/Character/index.tsx
  libs/zzz/ui/src/Disc/DiscFilter.tsx
  libs/zzz/ui/src/Disc/DiscFilterDisplay.tsx
  libs/zzz/ui/src/Disc/DiscInventory.tsx
  libs/zzz/ui/src/Disc/DiscLevelSlider.tsx
  libs/zzz/ui/src/Disc/DiscMainStatMultiAutocomplete.tsx
  libs/zzz/ui/src/Disc/DiscSetMultiAutocomplete.tsx
  libs/zzz/ui/src/Disc/SubstatMultiAutocomplete.tsx
  libs/zzz/ui/src/Disc/index.tsx
  libs/zzz/ui/src/context/SillyContext.tsx
  libs/zzz/ui/src/context/index.ts
  libs/zzz/ui/src/toggles/DiscSlotToggle.tsx
  libs/zzz/ui/src/toggles/index.ts
  libs/zzz/util/.eslintrc.json
  libs/zzz/util/README.md
  libs/zzz/util/jest.config.ts
  libs/zzz/util/package.json
  libs/zzz/util/project.json
  libs/zzz/util/src/disc/disc.ts
  libs/zzz/util/src/disc/discSortUtil.ts
  libs/zzz/util/src/disc/index.ts
  libs/zzz/util/src/index.ts
  libs/zzz/util/src/level.ts
  libs/zzz/util/tsconfig.eslint.json
  libs/zzz/util/tsconfig.json
  libs/zzz/util/tsconfig.lib.json
  libs/zzz/util/tsconfig.spec.json
  tsconfig.base.json
Labels: ZO

#2654 ZO add advanced Set Filters
  libs/common/util/src/lib/object.ts
  libs/zzz/db/src/Database/DataManagers/CharacterDataManager.ts
  libs/zzz/page-optimize/src/BuildsDisplay.tsx
  libs/zzz/page-optimize/src/CharacterContext.ts
  libs/zzz/page-optimize/src/LevelFilter.tsx
  libs/zzz/page-optimize/src/Optimize.tsx
  libs/zzz/page-optimize/src/SetFilter.tsx
  libs/zzz/page-optimize/src/index.tsx
  libs/zzz/solver/src/calc.ts
  libs/zzz/solver/src/childWorker.ts
  libs/zzz/solver/src/common.ts
  libs/zzz/solver/src/parentWorker.ts
  libs/zzz/solver/src/solver.ts
Labels: ZO
