Repository frzyc/genshin-optimizer, pull requests merged in 2025-03, with the labels that each got.

#2824 ZO: Fix Set Filter
  libs/zzz/solver-pando/src/solver.ts
Labels: bug, showDevComponents, ZO

#2823 ZO: M4 - Wengine Opt Filters
  libs/zzz/db/src/Database/DataManagers/OptConfigDataManager.ts
  libs/zzz/page-optimize-pando/src/Optimize/WengineFilter.tsx
  libs/zzz/page-optimize-pando/src/Optimize/WengineLevelFilter.tsx
  libs/zzz/page-optimize-pando/src/Optimize/index.tsx
  libs/zzz/ui/src/Wengine/WengineLevelSlider.tsx
  libs/zzz/ui/src/Wengine/index.ts
Labels: showDevComponents, ZO

#2815 GameOpt: Improve `Solver` responsiveness
  libs/game-opt/solver/src/common.ts
  libs/game-opt/solver/src/index.ts
  libs/game-opt/solver/src/solver.ts
  libs/game-opt/solver/src/worker.ts
  libs/game-opt/solver/src/workerHandle.ts
  libs/sr/page-optimize/src/Optimize/index.tsx
  libs/sr/page-team/src/Optimize/index.tsx
  libs/sr/solver/src/solver.ts
  libs/zzz/page-optimize-pando/src/Optimize/index.tsx
  libs/zzz/solver-pando/src/solver.ts
Labels: showDevComponents, game-opt

#2827 GameOpt: Improve `Solver` speed
  libs/game-opt/solver/project.json
  libs/game-opt/solver/src/solver.ts
  libs/game-opt/solver/src/split.ts
  libs/game-opt/solver/src/worker.spec.ts
  libs/game-opt/solver/src/worker.ts
  libs/game-opt/solver/src/workerHandle.ts
  libs/game-opt/solver/tsconfig.json
  libs/game-opt/solver/tsconfig.spec.json
  libs/game-opt/solver/vitest.config.ts
  libs/pando/engine/src/node/transform.spec.ts
  libs/pando/engine/src/node/transform.ts
  libs/pando/engine/src/optimization/prune.spec.ts
  libs/pando/engine/src/optimization/prune.ts
  libs/pando/engine/src/util/custom.ts
  libs/pando/engine/src/util/index.ts
Labels: game-opt

#2775 Somnia Bot: add talent scalings to archive char command
  apps/somnia/src/commands/archive.ts
  apps/somnia/src/commands/archive/char.ts
  apps/somnia/src/commands/archive/weapon.ts
  apps/somnia/src/commands/go/calculator.ts
  libs/gi/consts/src/character.ts
  libs/gi/dm-localization/assets/locales/chs/charNames_gen.json
  libs/gi/dm-localization/assets/locales/cht/charNames_gen.json
  libs/gi/dm-localization/assets/locales/de/charNames_gen.json
  libs/gi/dm-localization/assets/locales/en/charNames_gen.json
  libs/gi/dm-localization/assets/locales/es/charNames_gen.json
  libs/gi/dm-localization/assets/locales/fr/charNames_gen.json
  libs/gi/dm-localization/assets/locales/id/charNames_gen.json
  libs/gi/dm-localization/assets/locales/it/charNames_gen.json
  libs/gi/dm-localization/assets/locales/ja/charNames_gen.json
  libs/gi/dm-localization/assets/locales/ko/charNames_gen.json
  libs/gi/dm-localization/assets/locales/pt/charNames_gen.json
  libs/gi/dm-localization/assets/locales/ru/charNames_gen.json
  libs/gi/dm-localization/assets/locales/th/charNames_gen.json
  libs/gi/dm-localization/assets/locales/tr/charNames_gen.json
  libs/gi/dm-localization/assets/locales/vi/charNames_gen.json
  libs/gi/dm-localization/src/executors/gen-locale/executor.ts
  libs/gi/i18n-node/src/i18n.ts
  libs/gi/stats/src/index.ts
  package.json
Labels: somnia

#2832 ZO: Fix disc editor after reopen
  libs/zzz/page-discs/src/index.tsx
Labels: ZO

#2833 SRO/ZO: Add footer to SR and ZZZ
  apps/sr-frontend/src/app/App.tsx
  apps/sr-frontend/src/app/Footer.tsx
  apps/zzz-frontend/src/app/App.tsx
  apps/zzz-frontend/src/app/Footer.tsx
Labels: SRO, ZO

#2829 SRO: Implement floor
  libs/game-opt/engine/src/index.ts
  libs/game-opt/formula-ui/src/context/CalcContext.ts
  libs/game-opt/sheet-ui/src/types/conditional.ts
  libs/sr/formula/src/calculator.ts
  libs/sr/formula/src/formulaText.ts
  libs/sr/formula/src/util.ts
Labels: SRO

#2834 GameOpt: Update `Calculator` metadata
  libs/game-opt/engine/src/calculator.ts
  libs/game-opt/engine/src/index.ts
  libs/game-opt/formula-ui/src/context/CalcContext.ts
  libs/game-opt/sheet-ui/src/types/conditional.ts
  libs/gi/formula/src/calculator.ts
  libs/gi/formula/src/formulaText.ts
  libs/gi/formula/src/index.ts
  libs/pando/engine/src/debug.ts
  libs/pando/engine/src/node/calc.ts
  libs/pando/engine/src/tag/compilation.ts
  libs/pando/engine/src/tag/subset.ts
  libs/pando/engine/src/tag/symb.ts
  libs/sr/formula/src/calculator.ts
  libs/sr/formula/src/formulaText.ts
  libs/sr/formula/src/index.ts
  libs/sr/page-optimize/src/CharCalcProvider.tsx
  libs/sr/page-team/src/TeamCalcProvider.tsx
  libs/zzz/formula/src/calculator.ts
  libs/zzz/formula/src/formulaText.ts
  libs/zzz/page-optimize-pando/src/CharCalcProvider.tsx
Labels: game-opt

#2831 ZO: Compact grid implementation
  apps/zzz-frontend/src/main.tsx
  libs/zzz/assets/src/common/phases/SINGLE_NON_PHASE.png
  libs/zzz/assets/src/common/phases/SINGLE_PHASE.png
  libs/zzz/assets/src/common/phases/index.ts
  libs/zzz/assets/src/index.ts
  libs/zzz/page-optimize-pando/src/CharacterOptDisplay.tsx
  libs/zzz/page-optimize-pando/src/Optimize/EquippedGrid.tsx
  libs/zzz/svgicons/src/components/SlotIcon.tsx
  libs/zzz/svgicons/src/components/index.ts
  libs/zzz/svgicons/src/icons/Slots/Slot1Icon.tsx
  libs/zzz/svgicons/src/icons/Slots/Slot2Icon.tsx
  libs/zzz/svgicons/src/icons/Slots/Slot3Icon.tsx
  libs/zzz/svgicons/src/icons/Slots/Slot4Icon.tsx
  libs/zzz/svgicons/src/icons/Slots/Slot5Icon.tsx
  libs/zzz/svgicons/src/icons/Slots/Slot6Icon.tsx
  libs/zzz/svgicons/src/icons/Slots/index.ts
  libs/zzz/svgicons/src/icons/index.ts
  libs/zzz/theme/src/Theme.tsx
  libs/zzz/ui/src/Disc/CompactDiscCard.tsx
  libs/zzz/ui/src/Disc/DiscCard.tsx
  libs/zzz/ui/src/Disc/index.tsx
  libs/zzz/ui/src/Disc/util.ts
  libs/zzz/ui/src/Wengine/CompactWengineCard.tsx
  libs/zzz/ui/src/Wengine/WengineSubstatDisplay.tsx
  libs/zzz/ui/src/Wengine/index.ts
  libs/zzz/ui/src/util/EmptyCompactCard.tsx
  libs/zzz/ui/src/util/index.tsx
Labels: showDevComponents, ZO

#2837 ZO: Active card sets compact
  libs/zzz/page-optimize-pando/src/Optimize/EquippedGrid.tsx
  libs/zzz/ui/src/Disc/DiscSetCardCompact.tsx
  libs/zzz/ui/src/Disc/index.tsx
  libs/zzz/ui/src/util/EmptyCompactCard.tsx
Labels: showDevComponents, ZO

#2836 ZO: Update generated build equip grid
  libs/zzz/page-optimize-pando/src/CharacterOptDisplay.tsx
  libs/zzz/page-optimize-pando/src/Optimize/EquippedGrid.tsx
  libs/zzz/page-optimize-pando/src/Optimize/GeneratedBuildsDisplay.tsx
  libs/zzz/page-wengines/src/index.tsx
  libs/zzz/ui/src/Character/EquipGrid.tsx
  libs/zzz/ui/src/Character/EquipRow.tsx
  libs/zzz/ui/src/Character/EquippedGrid.tsx
  libs/zzz/ui/src/Character/index.tsx
  libs/zzz/ui/src/Components/ZCard.tsx
  libs/zzz/ui/src/Disc/CompactDiscCard.tsx
  libs/zzz/ui/src/Disc/DiscEditor/DiscEditor.tsx
  libs/zzz/ui/src/Disc/DiscInventory.tsx
  libs/zzz/ui/src/Disc/DiscSetCardCompact.tsx
  libs/zzz/ui/src/Disc/DiscSwapModal.tsx
  libs/zzz/ui/src/Wengine/CompactWengineCard.tsx
  libs/zzz/ui/src/Wengine/WengineSwapModal.tsx
  libs/zzz/ui/src/compactConst.ts
  libs/zzz/ui/src/index.tsx
  libs/zzz/ui/src/util/EmptyCompactCard.tsx
Labels: showDevComponents, ZO

#2828 ZO: formula display
  libs/zzz/formula-ui/src/char/components/OptimizationTargetSelector.tsx
  libs/zzz/formula-ui/src/char/components/index.ts
  libs/zzz/formula-ui/src/components/TagDisplay.tsx
  libs/zzz/formula-ui/src/components/index.ts
  libs/zzz/formula-ui/src/formulaText.tsx
  libs/zzz/formula-ui/src/index.ts
  libs/zzz/formula/src/formulaText.ts
  libs/zzz/page-optimize-pando/src/CharStatsDisplay.tsx
  libs/zzz/page-optimize-pando/src/CharacterOptDisplay.tsx
Labels: ZO

#2839 ZO: Update shape of zzz formulas for display
  libs/zzz/formula-ui/src/components/TagDisplay.tsx
  libs/zzz/formula-ui/src/formulaText.tsx
  libs/zzz/formula-ui/src/util.tsx
  libs/zzz/formula/src/data/common/dmg.ts
  libs/zzz/formula/src/data/common/prep.ts
  libs/zzz/formula/src/data/util/tag.ts
Labels: showDevComponents, ZO

#2851 GO: Speed up some builds
  libs/gi/solver/src/GOSolver/BNBSplitWorker/polyUB.ts
Labels: GO

#2848 ZO: added mindscapes to the char opt display
  libs/zzz/localization/assets/locales/en/page_characters.json
  libs/zzz/page-characters/src/index.tsx
  libs/zzz/page-optimize-pando/src/CharacterOptDisplay.tsx
  libs/zzz/ui/src/Character/CharacterProfilePieces.tsx
  libs/zzz/ui/src/Character/CharacterSelectionModal.tsx
  libs/zzz/ui/src/Character/editor/Content.tsx
  libs/zzz/ui/src/Disc/DiscSetCardCompact.tsx
  libs/zzz/ui/src/Wengine/CompactWengineCard.tsx
  libs/zzz/ui/src/util/EmptyCompactCard.tsx
Labels: showDevComponents, ZO

#2854 ZO: minor update to formula display
  libs/zzz/consts/src/common.ts
  libs/zzz/formula-ui/src/char/CharBase.tsx
  libs/zzz/formula-ui/src/components/TagDisplay.tsx
  libs/zzz/page-optimize-pando/src/CharStatsDisplay.tsx
  libs/zzz/svgicons/src/icons/Elements/ElectricIcon.tsx
  libs/zzz/svgicons/src/icons/Elements/EtherIcon.tsx
  libs/zzz/svgicons/src/icons/Elements/FireIcon.tsx
  libs/zzz/svgicons/src/icons/Elements/FrostIcon.tsx
  libs/zzz/svgicons/src/icons/Elements/IceIcon.tsx
  libs/zzz/svgicons/src/icons/Elements/PhysicalIcon.tsx
  libs/zzz/ui/src/Character/StatDisplay.tsx
Labels: ZO

#2855 ZO: Added font inter
  .yarn/cache/@fontsource-inter-npm-5.2.5-baa087c3c7-c1ac0a7379.zip
  apps/zzz-frontend/src/main.tsx
  libs/zzz/theme/src/Theme.tsx
  package.json
  yarn.lock
Labels: ZO

#2857 ZO: minor M3 opt UI update
  libs/zzz/consts/src/common.ts
  libs/zzz/db/src/Database/DataManagers/CharacterDataManager.ts
  libs/zzz/db/src/Interfaces/IZZZChracter.ts
  libs/zzz/page-optimize/src/Optimize.tsx
  libs/zzz/page-optimize/src/OptimizeTargetSelector.tsx
  libs/zzz/page-optimize/src/index.tsx
  libs/zzz/page-optimize/tsconfig.json
Labels: ZO

#2859 Refactor solver types and update solver progress calculation
  libs/game-opt/solver/src/common.ts
  libs/game-opt/solver/src/index.ts
  libs/game-opt/solver/src/solver.ts
  libs/game-opt/solver/src/split.ts
  libs/game-opt/solver/src/worker.spec.ts
  libs/game-opt/solver/src/worker.ts
  libs/sr/page-optimize/src/Optimize/index.tsx
  libs/sr/page-team/src/Optimize/index.tsx
  libs/sr/solver/src/solver.ts
  libs/zzz/page-optimize-pando/src/Optimize/index.tsx
  libs/zzz/solver-pando/src/index.ts
  libs/zzz/solver-pando/src/solver.ts
Labels: showDevComponents, game-opt

#2860 ZO: Character card and mindscape selector overhaul
  libs/zzz/page-characters/src/index.tsx
  libs/zzz/page-optimize-pando/src/CharacterOptDisplay.tsx
  libs/zzz/theme/src/Theme.tsx
  libs/zzz/ui/src/Character/CharacterCard.tsx
  libs/zzz/ui/src/Character/CharacterProfilePieces.tsx
  libs/zzz/ui/src/Character/editor/Content.tsx
  libs/zzz/ui/src/Components/MindscapesSwitch.tsx
  libs/zzz/ui/src/Components/index.ts
Labels: showDevComponents, ZO

#2858 ZO: M4 opt UI changes
  libs/zzz/db/src/Database/DataManagers/CharacterDataManager.ts
  libs/zzz/db/src/Database/DataManagers/CharacterOptManager.ts
  libs/zzz/db/src/Database/DataManagers/WengineDataManager.ts
  libs/zzz/db/src/Interfaces/IZZZChracter.ts
  libs/zzz/formula-ui/src/char/components/OptimizationTargetEditorList.tsx
  libs/zzz/formula-ui/src/char/components/OptimizationTargetSelector.tsx
  libs/zzz/formula-ui/src/char/components/StatFilterCard.tsx
  libs/zzz/formula-ui/src/char/components/index.ts
  libs/zzz/formula/src/util.ts
  libs/zzz/page-optimize-pando/src/BonusStats.tsx
  libs/zzz/page-optimize-pando/src/CharCalcProvider.tsx
  libs/zzz/page-optimize-pando/src/CharacterOptDisplay.tsx
  libs/zzz/page-optimize-pando/src/OptSelector.tsx
  libs/zzz/page-optimize-pando/src/Optimize/GeneratedBuildsDisplay.tsx
  libs/zzz/page-optimize-pando/src/Optimize/StatFilterCard.tsx
  libs/zzz/page-optimize-pando/src/Optimize/index.tsx
  libs/zzz/page-optimize-pando/src/index.tsx
  libs/zzz/solver-pando/src/index.ts
  libs/zzz/ui/src/Character/EquippedGrid.tsx
  libs/zzz/ui/src/Character/editor/Content.tsx
Labels: showDevComponents, ZO

#2863 ZO: add enemy editor
  libs/zzz/consts/src/common.ts
  libs/zzz/db/src/Database/DataManagers/CharacterOptManager.ts
  libs/zzz/formula-ui/src/char/components/OptimizationTargetSelector.tsx
  libs/zzz/formula-ui/src/char/util.ts
  libs/zzz/page-optimize-pando/src/CharCalcProvider.tsx
  libs/zzz/page-optimize-pando/src/CharStatsDisplay.tsx
  libs/zzz/page-optimize-pando/src/CharacterOptDisplay.tsx
  libs/zzz/page-optimize-pando/src/CritModeSelector.tsx
  libs/zzz/page-optimize-pando/src/EnemyCard.tsx
  libs/zzz/page-optimize-pando/src/index.tsx
  libs/zzz/ui/src/Character/editor/Content.tsx
Labels: showDevComponents, ZO

#2864 ZO: add specific dmg type to standard dmg target
  libs/zzz/db/src/Database/DataManagers/CharacterOptManager.ts
  libs/zzz/formula-ui/src/char/CharBase.tsx
  libs/zzz/formula-ui/src/char/components/OptimizationTargetSelector.tsx
  libs/zzz/formula-ui/src/char/util.ts
  libs/zzz/formula-ui/src/components/TagDisplay.tsx
  libs/zzz/formula/src/data/char/util.ts
  libs/zzz/formula/src/meta.ts
  libs/zzz/formula/src/util.ts
  libs/zzz/page-optimize-pando/src/BonusStats.tsx
  libs/zzz/page-optimize-pando/src/CharCalcProvider.tsx
  libs/zzz/page-optimize-pando/src/CharStatsDisplay.tsx
  libs/zzz/page-optimize-pando/src/OptSelector.tsx
  libs/zzz/page-optimize-pando/src/Optimize/index.tsx
  libs/zzz/page-optimize-pando/src/SpecificDmgTypeSelector.tsx
  libs/zzz/page-optimize-pando/src/index.tsx
  libs/zzz/ui/src/Wengine/CompactWengineCard.tsx
  libs/zzz/ui/src/util/EmptyCompactCard.tsx
Labels: showDevComponents, ZO

#2868 ZO: add gear conditional UIs for solver
  libs/zzz/page-optimize-pando/src/CharCalcProvider.tsx
  libs/zzz/page-optimize-pando/src/Optimize/DiscFilter.tsx
  libs/zzz/page-optimize-pando/src/Optimize/DiscSetFilter.tsx
  libs/zzz/page-optimize-pando/src/Optimize/WengineFilter.tsx
Labels: showDevComponents, ZO

#2869 ZO: Add Disc sheets from 1.6
  libs/zzz/formula-ui/src/disc/sheets/AstralVoice.tsx
  libs/zzz/formula-ui/src/disc/sheets/BranchBladeSong.tsx
  libs/zzz/formula-ui/src/disc/sheets/ChaosJazz.tsx
  libs/zzz/formula-ui/src/disc/sheets/ChaoticMetal.tsx
  libs/zzz/formula-ui/src/disc/sheets/FangedMetal.tsx
  libs/zzz/formula-ui/src/disc/sheets/HormonePunk.tsx
  libs/zzz/formula-ui/src/disc/sheets/InfernoMetal.tsx
  libs/zzz/formula-ui/src/disc/sheets/PhaethonsMelody.tsx
  libs/zzz/formula-ui/src/disc/sheets/ProtoPunk.tsx
  libs/zzz/formula-ui/src/disc/sheets/PufferElectro.tsx
  libs/zzz/formula-ui/src/disc/sheets/ShadowHarmony.tsx
  libs/zzz/formula-ui/src/disc/sheets/SwingJazz.tsx
  libs/zzz/formula-ui/src/disc/sheets/ThunderMetal.tsx
  libs/zzz/formula-ui/src/disc/sheets/WoodpeckerElectro.tsx
  libs/zzz/formula-ui/src/util.tsx
  libs/zzz/formula/src/data/disc/disc.test.ts
  libs/zzz/formula/src/data/disc/sheets/PhaethonsMelody.ts
  libs/zzz/formula/src/data/disc/sheets/ShadowHarmony.ts
  libs/zzz/formula/src/data/disc/util.ts
  libs/zzz/formula/src/meta.ts
  libs/zzz/localization/assets/locales/en/disc_PhaethonsMelody.json
  libs/zzz/localization/assets/locales/en/disc_ShadowHarmony.json
  libs/zzz/page-optimize-pando/src/CharCalcProvider.tsx
  libs/zzz/page-optimize-pando/src/discsTagMapNodes.ts
Labels: showDevComponents, ZO

#2866 ZO: Partitioned Char info into sections
  libs/zzz/localization/assets/locales/en/page_optimize.json
  libs/zzz/page-optimize-pando/src/BonusStats.tsx
  libs/zzz/page-optimize-pando/src/CharacterOptDisplay.tsx
Labels: showDevComponents, ZO

#2872 ZO: add wengine sheets to filter UI
  libs/zzz/page-optimize-pando/src/Optimize/WengineFilter.tsx
  libs/zzz/page-optimize-pando/src/Optimize/index.tsx
Labels: showDevComponents, ZO

#2870 ZO: add more options to bonus stats
  libs/zzz/db/src/Database/DataManagers/CharacterOptManager.ts
  libs/zzz/db/src/Database/DataManagers/WengineDataManager.ts
  libs/zzz/formula-ui/src/components/TagDisplay.tsx
  libs/zzz/formula-ui/src/components/index.ts
  libs/zzz/formula-ui/src/components/qtMap.ts
  libs/zzz/page-optimize-pando/src/BonusStats.tsx
  libs/zzz/page-optimize-pando/src/CharStatsDisplay.tsx
  libs/zzz/page-optimize-pando/src/DmgTypeDropdown.tsx
  libs/zzz/page-optimize-pando/src/Optimize/DiscFilter.tsx
  libs/zzz/page-optimize-pando/src/Optimize/DiscSetFilter.tsx
  libs/zzz/page-optimize-pando/src/SpecificDmgTypeSelector.tsx
Labels: showDevComponents, ZO

#2874 ZO: add wengine + disc cond UI
  libs/zzz/db-ui/src/hooks/index.ts
  libs/zzz/db-ui/src/hooks/useDiscSets.ts
  libs/zzz/formula-ui/src/disc/components/DiscSheetDisplay.tsx
  libs/zzz/formula-ui/src/wengine/components/WengineSheetDisplay.tsx
  libs/zzz/page-optimize-pando/src/BonusStats.tsx
  libs/zzz/page-optimize-pando/src/CharacterOptDisplay.tsx
  libs/zzz/page-optimize-pando/src/Optimize/DiscSetFilter.tsx
  libs/zzz/page-optimize-pando/src/Optimize/StatFilterCard.tsx
  libs/zzz/page-optimize-pando/src/Optimize/WengineFilter.tsx
  libs/zzz/page-optimize-pando/src/Optimize/index.tsx
  libs/zzz/page-optimize-pando/src/WengineSheetsDisplay.tsx
  libs/zzz/ui/src/Components/WorkerSelector.tsx
  libs/zzz/ui/src/Disc/DiscSetCardCompact.tsx
Labels: showDevComponents, ZO

#2875 ZO: Fix order of conditions for debug filtering
  libs/zzz/formula/src/data/wengine/util.ts
Labels: ZO

#2876 ZO: Fix Shadow Harmony 4p buff not being combat
  libs/zzz/consts/src/disc.ts
Labels: ZO

#2878 ZO: Add Bonus stats notes text field
  libs/zzz/localization/assets/locales/en/page_optimize.json
  libs/zzz/page-optimize-pando/src/BonusStats.tsx
Labels: showDevComponents, ZO

#2880 ZO: minor UI updates
  apps/zzz-frontend/src/app/Header.tsx
  libs/game-opt/sheet-ui/src/components/DocumentDisplay.tsx
  libs/zzz/formula-ui/src/disc/components/DiscSheetDisplay.tsx
  libs/zzz/formula-ui/src/wengine/components/WengineSheetDisplay.tsx
  libs/zzz/page-optimize-pando/src/CharacterOptDisplay.tsx
  libs/zzz/page-optimize-pando/src/Optimize/EquippedGrid.tsx
  libs/zzz/ui/src/Character/EquipGrid.tsx
Labels: showDevComponents, ZO

#2882 GO: Sort loadouts based on name
  libs/gi/page-team/src/LoadoutDropdown.tsx
  libs/gi/ui/src/components/character/editor/Content.tsx
Labels: GO

#2862 ZO: remove disc scanner support
  libs/zzz/db/src/driveDiskScanner.ts
  libs/zzz/db/src/index.ts
  libs/zzz/ui/src/Settings/UploadCard.tsx
Labels: ZO

#2883 ZO: Minor changes
  libs/zzz/db/src/Database/DataEntries/DBMetaEntry.ts
  libs/zzz/page-optimize-pando/src/BonusStats.tsx
  libs/zzz/page-optimize-pando/src/index.tsx
Labels: bug, showDevComponents, ZO

#2888 ZO: amend disc set check in specific sheets
  libs/zzz/formula/src/data/disc/sheets/ProtoPunk.ts
  libs/zzz/formula/src/data/disc/sheets/ThunderMetal.ts
  libs/zzz/formula/src/generators/gen-sheet/disc/__sheet__.ts.template
Labels: ZO

#2891 ZO: Character peage filters, sorts and style improvements
  libs/zzz/db/src/Database/DataEntries/DisplayCharacterEntry.ts
  libs/zzz/db/src/Database/Database.ts
  libs/zzz/localization/assets/locales/en/page_characters.json
  libs/zzz/page-characters/src/index.tsx
  libs/zzz/ui/src/Character/CharacterSort.ts
  libs/zzz/ui/src/Character/index.tsx
  libs/zzz/ui/src/toggles/CharacterRarityToggle.tsx
  libs/zzz/ui/src/toggles/CharacterSpecialtyToggle.tsx
  libs/zzz/ui/src/toggles/ElementToggle.tsx
  libs/zzz/ui/src/toggles/index.ts
Labels: ZO

#2889 ZO: Add stat highlight
  libs/zzz/formula-ui/src/char/CharBase.tsx
  libs/zzz/page-optimize/src/CharStatsDisplay.tsx
  libs/zzz/page-optimize/src/CharacterOptDisplay.tsx
  libs/zzz/ui/src/Character/EquipGrid.tsx
  libs/zzz/ui/src/Disc/CompactDiscCard.tsx
  libs/zzz/ui/src/Wengine/CompactWengineCard.tsx
  libs/zzz/ui/src/context/SillyContext.tsx
  libs/zzz/ui/src/context/StatHighlight.ts
  libs/zzz/ui/src/context/index.ts
  libs/zzz/ui/src/index.tsx
Labels: ZO

#2894 ZO: change statfilter symbols to min/max
  libs/zzz/page-optimize/src/Optimize/StatFilterCard.tsx
Labels: ZO

#2897 ZO: add enemy editor
  libs/zzz/consts/src/common.ts
  libs/zzz/db/src/Database/DataManagers/CharacterOptManager.ts
  libs/zzz/formula-ui/src/components/TagDisplay.tsx
  libs/zzz/localization/assets/locales/en/page_optimize.json
  libs/zzz/page-optimize/src/BonusStats.tsx
  libs/zzz/page-optimize/src/CharCalcProvider.tsx
  libs/zzz/page-optimize/src/CharacterOptDisplay.tsx
  libs/zzz/page-optimize/src/EnemyCard.tsx
  libs/zzz/page-optimize/src/EnemyStats.tsx
  libs/zzz/page-optimize/src/OptTargetRow/OptSelector.tsx
  libs/zzz/stats/src/char.ts
Labels: ZO

#2902 ZO: use character selection modal for opt page
  libs/zzz/page-optimize/src/OptTargetRow/index.tsx
  libs/zzz/page-optimize/src/index.tsx
  libs/zzz/ui/src/Character/CharIconCircleElement.tsx
  libs/zzz/ui/src/Character/CharacterSelectionModal.tsx
Labels: ZO

#2904 ZO: Added location icon to compact disc card
  libs/zzz/ui/src/Disc/CompactDiscCard.tsx
Labels: ZO

#2900 Pando: Update `DebugCalculator`
  libs/game-opt/engine/src/calculator.ts
  libs/game-opt/formula/src/debug.ts
  libs/game-opt/solver/src/debug.ts
  libs/game-opt/solver/src/index.ts
  libs/gi/formula/src/example.test.ts
  libs/pando/engine/src/debug.ts
  libs/pando/engine/src/node/calc.ts
  libs/pando/engine/src/node/formula.ts
  libs/pando/engine/src/node/transform.ts
  libs/pando/engine/src/optimization/prune.spec.ts
  libs/pando/engine/src/optimization/prune.ts
  libs/pando/engine/src/optimization/simplify.ts
  libs/zzz/formula/src/formula.test.ts
Labels: showDevComponents

#2910 ZO: Update formula display
  libs/game-opt/sheet-ui/src/components/FieldDisplay.tsx
  libs/game-opt/sheet-ui/src/context/FormulaTextCacheContext.ts
  libs/game-opt/sheet-ui/src/context/FormulaTextContext.ts
  libs/game-opt/sheet-ui/src/context/FullTagDisplayContext.ts
  libs/game-opt/sheet-ui/src/context/TagDisplayContext.ts
  libs/game-opt/sheet-ui/src/context/index.ts
  libs/game-opt/sheet-ui/src/types/formulaText.ts
  libs/game-opt/sheet-ui/src/types/index.ts
  libs/pando/engine/src/tag/keys.ts
  libs/zzz/formula-ui/src/char/tagFieldMap.ts
  libs/zzz/formula-ui/src/components/TagDisplay.tsx
  libs/zzz/formula-ui/src/formulaText.tsx
  libs/zzz/formula/src/data/disc/sheets/AstralVoice.ts
  libs/zzz/formula/src/data/disc/sheets/BranchBladeSong.ts
  libs/zzz/formula/src/data/disc/sheets/ChaosJazz.ts
  libs/zzz/formula/src/data/disc/sheets/ChaoticMetal.ts
  libs/zzz/formula/src/data/disc/sheets/FangedMetal.ts
  libs/zzz/formula/src/data/disc/sheets/HormonePunk.ts
  libs/zzz/formula/src/data/disc/sheets/InfernoMetal.ts
  libs/zzz/formula/src/data/disc/sheets/PhaethonsMelody.ts
  libs/zzz/formula/src/data/disc/sheets/PolarMetal.ts
  libs/zzz/formula/src/data/disc/sheets/ProtoPunk.ts
  libs/zzz/formula/src/data/disc/sheets/PufferElectro.ts
  libs/zzz/formula/src/data/disc/sheets/ShadowHarmony.ts
  libs/zzz/formula/src/data/disc/sheets/ShockstarDisco.ts
  libs/zzz/formula/src/data/disc/sheets/SwingJazz.ts
  libs/zzz/formula/src/data/disc/sheets/ThunderMetal.ts
  libs/zzz/formula/src/data/disc/sheets/WoodpeckerElectro.ts
  libs/zzz/formula/src/data/util/read.ts
  libs/zzz/formula/src/data/wengine/sheets/BashfulDemon.ts
  libs/zzz/formula/src/generators/gen-sheet/disc/__sheet__.ts.template
  libs/zzz/formula/src/generators/gen-sheet/wengine/__sheet__.ts.template
  libs/zzz/page-optimize/src/CharCalcProvider.tsx
  libs/zzz/page-optimize/src/CharStatsDisplay.tsx
  libs/zzz/page-optimize/src/index.tsx
Labels: ZO

#2916 GO: Fix Iansan/Varesa bugs
  libs/gi/localization/assets/locales/en/char_Varesa.json
  libs/gi/sheets/src/Characters/Iansan/index.tsx
  libs/gi/sheets/src/Characters/Varesa/index.tsx
Labels: GO

#2912 ZO: Added builds selector
  libs/zzz/db/src/Database/DataManagers/OptConfigDataManager.ts
  libs/zzz/localization/assets/locales/en/page_optimize.json
  libs/zzz/page-optimize/src/Optimize/index.tsx
  libs/zzz/solver/src/index.ts
  libs/zzz/ui/src/Components/BuildsSelector.tsx
  libs/zzz/ui/src/Components/WorkerSelector.tsx
  libs/zzz/ui/src/Components/index.ts
Labels: ZO

#2919 ZO: Add show dupes modal
  libs/zzz/page-discs/src/DupModal.tsx
  libs/zzz/page-discs/src/index.tsx
  libs/zzz/ui/src/Disc/DiscInventory.tsx
Labels: ZO
